/** Este arquivo centraliza os contratos de dados do Catálogo Inteligente. O projeto usa JavaScript, portanto os tipos são documentados com JSDoc. */
/** @typedef {'pdf'|'excel'|'csv'|'manual'} CatalogImportType */
/** @typedef {'high'|'medium'|'low'|'not_found'} ExtractionConfidence */
/** @typedef {Object} ConfidenceField @property {*} value @property {ExtractionConfidence} confidence @property {string|null} [rawValue] @property {string|null} [warning] */
/** @typedef {Object} ProductDimensions @property {number|null} a @property {number|null} b @property {number|null} c @property {number|null} width @property {number|null} height @property {number|null} thickness @property {number|null} externalDiameter @property {number|null} internalDiameter @property {number|null} length @property {'mm'|'cm'|'m'|'in'} unit @property {string|null} originalText */
/** @typedef {Object} CatalogSource @property {string|null} importId @property {string|null} supplierId @property {string} supplierName @property {string|null} catalogName @property {string|null} catalogVersion @property {string|null} originalFileName @property {number|null} page @property {string|null} section @property {string|null} rawText @property {string|null} imageReference @property {string} importedAt @property {string|null} importedBy */
/** @typedef {Object} CommercialData @property {number|null} costPerKg @property {number|null} pricePerKg @property {number|null} pricePerMeter @property {number|null} pricePerPiece @property {string} currency @property {number|null} stockQuantity @property {number|null} minimumOrder @property {string|null} salesUnit @property {number|null} leadTimeDays @property {string|null} notes */
/** @typedef {Object} TechnicalData @property {number|null} weightPerMeter @property {number|null} weightPerPiece @property {string|null} weightUnit @property {ProductDimensions} dimensions @property {string|null} alloy @property {string|null} temper @property {string|null} finish @property {string|null} color @property {string|null} standard @property {string|null} application */
/** @typedef {Object} ExtractedCatalogProduct @property {string} id @property {string|null} existingProductId @property {string} supplierName @property {string|null} supplierCode @property {string|null} marketCode @property {string} name @property {string} description @property {string} productType @property {string} category @property {string|null} subcategory @property {string|null} commercialLine @property {string|null} family @property {string} status @property {TechnicalData} technical @property {CommercialData} commercial @property {CatalogSource} source @property {Object.<string, ConfidenceField>} confidence @property {string[]} synonyms @property {string[]} warnings @property {boolean} selected @property {'create'|'update'|'ignore'|'review'} duplicateAction @property {string|null} duplicateOf @property {string} createdAt @property {string} updatedAt */
/** @typedef {Object} CatalogImportDraft @property {string} id @property {CatalogImportType} type @property {string} status @property {string} supplierName @property {string|null} supplierId @property {string|null} catalogName @property {string|null} catalogVersion @property {string|null} originalFileName @property {number|null} totalPages @property {number} processedPages @property {ExtractedCatalogProduct[]} products @property {string[]} errors @property {string[]} warnings @property {string} companyId @property {string} userId @property {string} createdAt @property {string} updatedAt */
export {};
