import { useState } from "react";
import { EmptyState, MetricGrid } from "../../../components/operations/OperationsUI";
import OrcamentoFilters from "../components/OrcamentoFilters";
import OrcamentoHeader from "../components/OrcamentoHeader";
import OrcamentoTable from "../components/OrcamentoTable";
import useOrcamentos from "../hooks/useOrcamentos";
import NovoOrcamentoPage from "./NovoOrcamentoPage";
import OrcamentoDetailsPage from "./OrcamentoDetailsPage";
import PropostaPreviewPage from "./PropostaPreviewPage";
import HistoricoOrcamentoPage from "./HistoricoOrcamentoPage";
import AprovacaoOrcamentoPage from "./AprovacaoOrcamentoPage";
import { formatMoney } from "../utils/money-calculations";
import "../orcamento-inteligente.css";

function consumeDraft() { try { const raw = sessionStorage.getItem("cunha-finance:quote-draft"); if (!raw) return null; sessionStorage.removeItem("cunha-finance:quote-draft"); return JSON.parse(raw); } catch { return null; } }
export default function OrcamentosPage({ empresaId, userId, onNavigate }) {
  const manager = useOrcamentos({ empresaId, userId }); const [screen, setScreen] = useState("list"); const [selectedId, setSelectedId] = useState(null); const [view, setView] = useState("table"); const [page, setPage] = useState(1); const [draft, setDraft] = useState(consumeDraft); const selected = manager.quotes.find((quote) => quote.id === selectedId) || null; const pageSize = 6; const pageCount = Math.max(1, Math.ceil(manager.filtered.length / pageSize)); const visible = manager.filtered.slice((page - 1) * pageSize, page * pageSize);
  async function save(quote) { const saved = await manager.saveQuote(quote); if (!saved) return; setDraft(null); setSelectedId(saved.id); setScreen("details"); }
  if (screen === "new" || draft) return <NovoOrcamentoPage initial={draft} onSave={save} onBack={() => { setDraft(null); setScreen("list"); }} />;
  if (screen === "proposal" && selected) return <PropostaPreviewPage empresaId={empresaId} quote={selected} onBack={() => setScreen("details")} onHistory={() => setScreen("history")} />;
  if (screen === "approval" && selected) return <AprovacaoOrcamentoPage quote={selected} onBack={() => setScreen("details")} onDecision={async (decision, observation) => { await manager.registerDecision(selected.id, decision, observation); setScreen("details"); }} />;
  if (screen === "history" && selected) return <HistoricoOrcamentoPage quote={selected} onBack={() => setScreen("proposal")} onHome={() => setScreen("list")} />;
  if (screen === "details" && selected) return <OrcamentoDetailsPage quote={selected} empresaId={empresaId} onBack={() => setScreen("list")} onStatus={manager.updateStatus} onOpportunity={() => onNavigate?.("crm")} onApproval={() => setScreen("approval")} onProposal={() => setScreen("proposal")} onHistory={() => setScreen("history")} />;
  const cards = [{ label: "Em aberto", value: manager.metrics.abertos, detail: "orçamentos ativos", icon: "▤" }, { label: "Emitidos", value: manager.metrics.emitidos, detail: "orçamentos reais", icon: "◎" }, { label: "Enviados", value: manager.metrics.enviados, detail: "com o cliente", icon: "↗" }, { label: "Aprovados", value: manager.metrics.aprovados, detail: `${manager.metrics.taxaAprovacao.toFixed(1)}% aprovação`, icon: "✓", tone: "green" }, { label: "Valor orçado", value: formatMoney(manager.metrics.valorOrcado), detail: "total persistido", icon: "R$" }, { label: "Valor aprovado", value: formatMoney(manager.metrics.valorAprovado), detail: "total aprovado", icon: "◆", tone: "green" }];
  return <main className="ops-page quote-page"><OrcamentoHeader onNew={() => setScreen("new")} /><div className="quote-demo-note"><span /> Persistência real isolada por empresa · confirmação humana obrigatória</div>{manager.error && <div className="ops-status-panel">{manager.error} A migration da Fase 17 precisa ser aplicada ao Supabase.</div>}{manager.loading && <div className="ops-status-panel">Carregando orçamentos persistentes...</div>}<MetricGrid items={cards} /><OrcamentoFilters filters={manager.filters} onChange={(filters) => { manager.setFilters(filters); setPage(1); }} onClear={manager.clearFilters} quotes={manager.quotes} /><div className="quote-viewbar"><div><strong>Central de Orçamentos</strong><span>{manager.filtered.length} resultado(s)</span></div><div><button className={view === "table" ? "active" : ""} onClick={() => setView("table")}>Tabela</button><button className={view === "cards" ? "active" : ""} onClick={() => setView("cards")}>Cards</button></div></div>{view === "table" ? <OrcamentoTable quotes={visible} onOpen={(quote) => { setSelectedId(quote.id); setScreen("details"); }} /> : visible.length ? <div className="quote-cards">{visible.map((quote) => <article key={quote.id} onClick={() => { setSelectedId(quote.id); setScreen("details"); }}><small>{quote.numero}</small><strong>{quote.cliente}</strong><span className="quote-status">{quote.status}</span><div><b>{formatMoney(quote.valor)}</b></div><footer>{quote.oportunidadeId ? "Vinculado ao CRM" : "Sem oportunidade"}<span>Validade {quote.validade}</span></footer></article>)}</div> : <section className="ops-panel"><EmptyState title="Nenhum orçamento encontrado" /></section>}<div className="quote-pagination"><button disabled={page === 1} onClick={() => setPage((current) => current - 1)}>Anterior</button><span>Página {page} de {pageCount}</span><button disabled={page === pageCount} onClick={() => setPage((current) => current + 1)}>Próxima</button></div></main>;
}
