import { supabase } from "../../../supabase";

const mapItem = (item) => ({ id: item.id, catalogoItemId: item.catalogo_item_id, codigo: item.produto, descricao: item.descricao || "", liga: item.liga || "", tempera: item.tempera || "", dimensoes: item.dimensao || "", pesoTotal: Number(item.peso || 0), quantidade: Number(item.quantidade || 0), unidade: item.unidade, preco: Number(item.preco_unitario || 0), subtotal: Number(item.subtotal || 0), dadosCatalogo: item.dados_catalogo || {} });
export function fromQuoteRecord(row) { return { id: row.id, numero: row.numero, empresaId: row.empresa_id, userId: row.user_id, clienteId: row.cliente_id, oportunidadeId: row.oportunidade_id, clienteSnapshot: row.cliente_snapshot || {}, cliente: row.cliente_snapshot?.nome || "Cliente", contato: row.cliente_snapshot?.contatoResponsavel || "", data: row.data, validade: row.validade, observacoesCliente: row.observacoes || "", observacoesInternas: row.observacoes_internas || "", desconto: Number(row.desconto || 0), impostos: Number(row.impostos || 0), comissao: Number(row.comissao || 0), subtotal: Number(row.subtotal || 0), valor: Number(row.valor_final || 0), status: row.status, condicaoPagamento: row.condicao_pagamento || "", prazoEntrega: row.prazo_entrega || "", modalidadeFrete: row.modalidade_frete || "", createdAt: row.created_at, updatedAt: row.updated_at, items: (row.orcamento_itens || []).map(mapItem), historico: row.orcamento_historico || [] }; }
export async function listQuotes(empresaId) { const { data, error } = await supabase.from("orcamentos").select("*, orcamento_itens(*), orcamento_historico(*)").eq("empresa_id", String(empresaId)).order("created_at", { ascending: false }); if (error) throw error; return (data || []).map(fromQuoteRecord); }
const quotePayload = (quote, empresaId, userId, totals) => ({ empresa_id: String(empresaId), user_id: userId, cliente_id: String(quote.clienteId), oportunidade_id: quote.oportunidadeId || null, numero: quote.numero, data: quote.data, validade: quote.validade, observacoes: quote.observacoesCliente || null, observacoes_internas: quote.observacoesInternas || null, desconto: totals.desconto, impostos: totals.impostos, comissao: totals.comissao, subtotal: totals.subtotal, valor_final: totals.valorFinal, status: quote.status, cliente_snapshot: quote.clienteSnapshot || {}, condicao_pagamento: quote.condicaoPagamento || null, prazo_entrega: quote.prazoEntrega || null, modalidade_frete: quote.modalidadeFrete || null, updated_at: new Date().toISOString() });
const itemPayload = (item, quoteId, empresaId) => ({ orcamento_id: quoteId, empresa_id: String(empresaId), catalogo_item_id: item.catalogoItemId ? String(item.catalogoItemId) : null, produto: item.codigo || item.descricao, descricao: item.descricao || null, liga: item.liga || null, tempera: item.tempera || null, dimensao: item.dimensoes || null, peso: Number(item.pesoTotal || 0), quantidade: Number(item.quantidade || 0), unidade: item.unidade || "kg", preco_unitario: Number(item.preco || 0), subtotal: Number(item.preco || 0) * Number(item.quantidade || 0), dados_catalogo: item.dadosCatalogo || {} });
export async function saveQuoteRecord({ quote, empresaId, userId, totals }) { const payload = quotePayload(quote, empresaId, userId, totals); const query = quote.id ? supabase.from("orcamentos").update(payload).eq("id", quote.id).eq("empresa_id", String(empresaId)) : supabase.from("orcamentos").insert(payload); const { data, error } = await query.select("*").single(); if (error) throw error; const { error: deleteError } = await supabase.from("orcamento_itens").delete().eq("orcamento_id", data.id).eq("empresa_id", String(empresaId)); if (deleteError) throw deleteError; if (quote.items.length) { const { error: itemsError } = await supabase.from("orcamento_itens").insert(quote.items.map((item) => itemPayload(item, data.id, empresaId))); if (itemsError) throw itemsError; } await addQuoteHistory({ quoteId: data.id, empresaId, userId, type: quote.id ? "Edição" : "Criação", description: quote.id ? "Orçamento editado após confirmação humana." : "Orçamento criado após confirmação humana." }); return data.id; }
export async function updateQuoteStatus({ quoteId, empresaId, userId, status }) { const { error } = await supabase.from("orcamentos").update({ status, updated_at: new Date().toISOString() }).eq("id", quoteId).eq("empresa_id", String(empresaId)); if (error) throw error; const types = { Enviado: "Envio", Aprovado: "Aprovação", Rejeitado: "Rejeição", Cancelado: "Cancelamento" }; await addQuoteHistory({ quoteId, empresaId, userId, type: types[status] || "Edição", description: `Status alterado para ${status}.` }); }
export async function addQuoteHistory({ quoteId, empresaId, userId, type, description }) { const { error } = await supabase.from("orcamento_historico").insert({ orcamento_id: quoteId, empresa_id: String(empresaId), user_id: userId, tipo: type, descricao: description }); if (error) throw error; }
export async function listQuotesByOpportunity(empresaId, opportunityId) { const { data, error } = await supabase.from("orcamentos").select("id,numero,status,valor_final,validade").eq("empresa_id", String(empresaId)).eq("oportunidade_id", opportunityId).order("created_at", { ascending: false }); if (error) throw error; return data || []; }
