const dateFromNow = (days) => { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
export const DEMO_ITEMS = [
  { id: "i1", codigo: "TR-6060-152", descricao: "Tarugo de alumínio 6060", liga: "6060", tempera: "Homogeneizado", formato: "Cilíndrico", dimensoes: "Ø 152 × 5800 mm", unidade: "kg", quantidade: 4200, pesoUnitario: 1, pesoPorMetro: 49.1, pesoPorBarra: 284.8, pesoTotal: 4200, fornecedor: "Liga Brasil", custo: 18.7, preco: 24.9, margem: 24.9, desconto: 0, observacoes: "Sob encomenda" },
  { id: "i2", codigo: "TR-6063-178", descricao: "Tarugo de alumínio 6063", liga: "6063", tempera: "Homogeneizado", formato: "Cilíndrico", dimensoes: "Ø 178 × 5800 mm", unidade: "barra", quantidade: 8, pesoUnitario: 389.8, pesoPorMetro: 67.2, pesoPorBarra: 389.8, pesoTotal: 3118.4, fornecedor: "Metal Forte", custo: 19.2, preco: 26.4, margem: 27.3, desconto: 2, observacoes: "Cotação válida por 7 dias" },
  { id: "i3", codigo: "TR-6351-203", descricao: "Tarugo de alumínio 6351", liga: "6351", tempera: "T6", formato: "Cilíndrico", dimensoes: "Ø 203 × 6000 mm", unidade: "kg", quantidade: 1800, pesoUnitario: 1, pesoPorMetro: 87.4, pesoPorBarra: 524.4, pesoTotal: 1800, fornecedor: "Alumax", custo: 22.8, preco: 31.5, margem: 27.6, desconto: 0, observacoes: "Liga especial" },
  { id: "i4", codigo: "PF-5030-N", descricao: "Perfil 50 × 30 natural", liga: "6063", tempera: "T5", formato: "Retangular", dimensoes: "50 × 30 × 2 × 6000 mm", unidade: "barra", quantidade: 120, pesoUnitario: 5.04, pesoPorMetro: 0.84, pesoPorBarra: 5.04, pesoTotal: 604.8, fornecedor: "Perfil Center", custo: 21.4, preco: 29.9, margem: 28.4, desconto: 0, observacoes: "Material de estoque" },
  { id: "i5", codigo: "SC-AL-M", descricao: "Sucata de alumínio mista", liga: "Mista", tempera: "—", formato: "Granel", dimensoes: "—", unidade: "kg", quantidade: 2500, pesoUnitario: 1, pesoPorMetro: 0, pesoPorBarra: 0, pesoTotal: 2500, fornecedor: "Recicla Sul", custo: 9.4, preco: 12.8, margem: 26.6, desconto: 0, observacoes: "Preço por kg" },
  { id: "i6", codigo: "PF-U2-AN", descricao: "Perfil U 2” anodizado", liga: "6063", tempera: "T6", formato: "U", dimensoes: "50,8 × 25 × 2,2 mm", unidade: "metro", quantidade: 480, pesoUnitario: 0.71, pesoPorMetro: 0.71, pesoPorBarra: 4.26, pesoTotal: 340.8, fornecedor: "Perfil Center", custo: 24.8, preco: 34.2, margem: 27.5, desconto: 1.5, observacoes: "Preço por metro" },
];
const base = { contato: "Compras", oportunidade: "Renovação de fornecimento", vendedor: "Marina Costa", moeda: "BRL", condicaoPagamento: "28 dias", prazoEntrega: "15 dias", modalidadeFrete: "CIF", origem: "Manual", margem: 26.8 };
const quotes = [
  { ...base, id: "ORC-2026-0142", cliente: "Metalúrgica Horizonte", status: "Em negociação", validade: dateFromNow(8), valor: 286400, createdAt: dateFromNow(-3), items: DEMO_ITEMS.slice(0, 3) },
  { ...base, id: "ORC-2026-0141", cliente: "Alumitech Componentes", vendedor: "Paulo Nunes", status: "Aguardando aprovação", validade: dateFromNow(12), valor: 142800, createdAt: dateFromNow(-5), origem: "CRM", items: DEMO_ITEMS.slice(3, 5) },
  { ...base, id: "ORC-2026-0140", cliente: "Fundição Vale Verde", status: "Enviado ao cliente", validade: dateFromNow(5), valor: 98500, createdAt: dateFromNow(-8), origem: "PDF", items: DEMO_ITEMS.slice(1, 2) },
  { ...base, id: "ORC-2026-0139", cliente: "Estruturas São Lucas", vendedor: "Diego Alves", status: "Aguardando análise", validade: dateFromNow(15), valor: 74400, createdAt: dateFromNow(-1), origem: "Imagem", items: DEMO_ITEMS.slice(3, 4) },
  { ...base, id: "ORC-2026-0138", cliente: "Indústria Nova Era", status: "Aceito", validade: dateFromNow(2), valor: 218000, createdAt: dateFromNow(-12), items: DEMO_ITEMS.slice(0, 2) },
  { ...base, id: "ORC-2026-0137", cliente: "Recicla Sul Metais", status: "Vencido", validade: dateFromNow(-4), valor: 52500, createdAt: dateFromNow(-20), items: DEMO_ITEMS.slice(4, 5) },
];
export function getDemoQuotes() { return quotes.map((quote) => ({ ...quote, items: quote.items.map((item) => ({ ...item })) })); }
export function createQuoteNumber(total) { return `ORC-2026-${String(143 + total).padStart(4, "0")}`; }
