import { useCallback, useEffect, useMemo, useState } from "react";
import { loadProduction } from "../services/producao.service";

export default function useProducao(empresaId) {
  const [data,setData]=useState({orders:[],stock:[],movements:[],sales:[],budgets:[],unavailable:{}});const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const refresh=useCallback(async()=>{if(!empresaId)return;setLoading(true);setError("");try{setData(await loadProduction(empresaId));}catch(reason){setError(reason.message||"Falha ao carregar Produção e PCP.");}finally{setLoading(false);}},[empresaId]);
  useEffect(()=>{refresh();},[refresh]);
  return useMemo(()=>{const today=new Date().toISOString().slice(0,10);const open=data.orders.filter((item)=>!["Concluída","Cancelada"].includes(item.status));const delayed=open.filter((item)=>item.data_prevista_fim&&item.data_prevista_fim<today);const missing=data.orders.flatMap((order)=>(order.ordem_producao_materiais||[]).filter((material)=>{const stock=data.stock.find((item)=>item.id===material.estoque_id);return Number(material.quantidade_prevista)-Number(material.quantidade_reservada)-Number(material.quantidade_consumida)>Number(stock?.estoque_disponivel||0)}).map((material)=>({order,material})));return{...data,loading,error,refresh,open,delayed,missing,inProduction:data.orders.filter((item)=>item.status==="Em produção"),completed:data.orders.filter((item)=>item.status==="Concluída"),planned:data.orders.reduce((sum,item)=>sum+Number(item.quantidade_planejada||0),0),produced:data.orders.reduce((sum,item)=>sum+Number(item.quantidade_produzida||0),0),plannedWeight:data.orders.reduce((sum,item)=>sum+Number(item.peso_planejado||0),0),producedWeight:data.orders.reduce((sum,item)=>sum+Number(item.peso_produzido||0),0),losses:data.orders.reduce((sum,item)=>sum+Number(item.quantidade_perdida||0),0)};},[data,error,loading,refresh]);
}
