import { supabase } from "../../../supabase";

export function describeSupabaseError(error) {
  const parts = [error?.message || "Erro desconhecido do Supabase"];
  if (error?.code) parts.push(`código ${error.code}`);
  if (error?.details) parts.push(`detalhes: ${error.details}`);
  if (error?.hint) parts.push(`orientação: ${error.hint}`);
  return parts.join(" · ");
}

function throwSupabaseError(context, error) {
  const technical = { context, code: error?.code, message: error?.message, details: error?.details, hint: error?.hint };
  console.error(`[CRM] ${context}`, technical, error);
  const enriched = new Error(`${context}: ${describeSupabaseError(error)}`);
  enriched.code = error?.code;
  enriched.details = error?.details;
  enriched.hint = error?.hint;
  enriched.cause = error;
  throw enriched;
}

export function fromDatabase(item) {
  return { id: item.id, clienteId: item.cliente_id, contatoPrincipal: item.cliente_nome || "", empresa: item.empresa_cliente || "", telefone: item.telefone || "", whatsapp: item.whatsapp || "", email: item.email || "", cidade: item.cidade || "", estado: item.estado || "", pais: item.pais || "", origemLead: item.origem || "", segmento: item.segmento || "", produtoInteresse: item.produto_material || "", quantidade: item.quantidade ?? "", pesoEstimado: item.quantidade ?? "", unidade: item.unidade || "kg", valorEstimado: Number(item.valor_estimado || 0), probabilidade: Number(item.probabilidade || 0), etapa: item.etapa, prioridade: item.prioridade, vendedorResponsavel: item.responsavel || "", proximoContato: item.previsao_fechamento || "", observacoes: item.observacoes || "", motivoPerda: item.motivo_perda || "", createdAt: item.created_at, updatedAt: item.updated_at, atividades: (item.crm_oportunidade_historico || []).map((entry) => ({ id: entry.id, tipo: entry.tipo, descricao: entry.descricao, data: String(entry.created_at).slice(0, 10) })) };
}
export function opportunityPayload(item, empresaId) { return { empresa_id: String(empresaId), cliente_id: item.clienteId ? String(item.clienteId) : null, cliente_nome: item.contatoPrincipal || null, empresa_cliente: item.empresa, telefone: item.telefone || null, whatsapp: item.whatsapp || null, email: item.email || null, cidade: item.cidade || null, estado: item.estado || null, pais: item.pais || null, origem: item.origemLead || null, segmento: item.segmento || null, produto_material: item.produtoInteresse || null, quantidade: item.pesoEstimado === "" ? null : Number(item.pesoEstimado), unidade: item.unidade || null, valor_estimado: Number(item.valorEstimado || 0), probabilidade: Number(item.probabilidade || 0), etapa: item.etapa, prioridade: item.prioridade, responsavel: item.vendedorResponsavel || null, previsao_fechamento: item.proximoContato || null, observacoes: item.observacoes || null, motivo_perda: item.motivoPerda || null }; }
export async function listOpportunities(empresaId) { const { data, error } = await supabase.from("crm_oportunidades").select("*, crm_oportunidade_historico(id,tipo,descricao,created_at)").eq("empresa_id", String(empresaId)).order("created_at", { ascending: false }); if (error) throwSupabaseError("Falha ao listar oportunidades",error); return (data || []).map(fromDatabase); }
export async function listCustomerOpportunities({ empresaId, customerId }) { if (!empresaId || !customerId) return []; const { data, error } = await supabase.from("crm_oportunidades").select("*, crm_oportunidade_historico(id,tipo,descricao,created_at)").eq("empresa_id", String(empresaId)).eq("cliente_id", String(customerId)).order("created_at", { ascending: false }); if (error) throwSupabaseError("Falha ao listar oportunidades do cliente", error); return (data || []).map(fromDatabase); }
export async function linkOpportunityCustomer({ empresaId, opportunityId, customerId }) { if (!empresaId || !opportunityId || !customerId) throw new Error("Empresa, oportunidade e cliente são obrigatórios para o vínculo."); const scope=String(empresaId); const { data: existing, error: readError }=await supabase.from("crm_oportunidades").select("id,cliente_id").eq("id",opportunityId).eq("empresa_id",scope).maybeSingle(); if(readError) throwSupabaseError("Falha ao validar oportunidade da prospecção",readError); if(!existing) throw new Error("A oportunidade vinculada à prospecção não foi encontrada nesta empresa."); if(existing.cliente_id && String(existing.cliente_id)!==String(customerId)) throw new Error("A oportunidade já está vinculada a outro cliente e não foi alterada."); if(existing.cliente_id) return existing; const { data,error }=await supabase.from("crm_oportunidades").update({cliente_id:String(customerId)}).eq("id",opportunityId).eq("empresa_id",scope).is("cliente_id",null).select("id,cliente_id").maybeSingle(); if(error) throwSupabaseError("Falha ao vincular cliente à oportunidade",error); if(!data) throw new Error("A oportunidade mudou durante o vínculo. Atualize a página e tente novamente."); return data; }
export async function addOpportunityHistory({ opportunityId, empresaId, userId, type, description }) { const { error } = await supabase.from("crm_oportunidade_historico").insert({ oportunidade_id: opportunityId, empresa_id: String(empresaId), user_id: userId, tipo: type, descricao: description }); if (error) throw error; }
async function recordHistoryBestEffort(args) { try { await addOpportunityHistory(args); return null; } catch (error) { console.error("Oportunidade salva, mas o histórico não foi registrado:", error); return error; } }
export async function saveOpportunityRecord({ opportunity, empresaId, userId }) { const payload = opportunityPayload(opportunity, empresaId); const insertPayload={...payload,user_id:userId}; console.info("[CRM] Gravando oportunidade",{mode:opportunity.id?"update":"insert",empresaId:String(empresaId),columns:Object.keys(opportunity.id?payload:insertPayload)}); const query = opportunity.id ? supabase.from("crm_oportunidades").update(payload).eq("id", opportunity.id).eq("empresa_id", String(empresaId)) : supabase.from("crm_oportunidades").insert(insertPayload); const { data, error } = await query.select("*").single(); if (error) throwSupabaseError(opportunity.id?"Falha ao atualizar oportunidade":"Falha ao inserir oportunidade",error); if(!data?.id) throwSupabaseError("Supabase não confirmou a oportunidade",{code:"CRM_NO_ROW",message:"A gravação não retornou uma linha com ID."}); console.info("[CRM] Oportunidade confirmada pelo Supabase",{id:data.id,empresa_id:data.empresa_id}); const historyError = await recordHistoryBestEffort({ opportunityId: data.id, empresaId, userId, type: opportunity.id ? "Edição" : "Criação", description: opportunity.id ? "Oportunidade atualizada após confirmação humana." : "Oportunidade criada após confirmação humana." }); return { ...fromDatabase(data), historyWarning: historyError ? "Oportunidade salva sem registro no histórico." : "" }; }
export async function updateOpportunityStage({ id, stage, empresaId, userId }) { const { error } = await supabase.from("crm_oportunidades").update({ etapa: stage }).eq("id", id).eq("empresa_id", String(empresaId)); if (error) throw error; return recordHistoryBestEffort({ opportunityId: id, empresaId, userId, type: stage === "Fechado — ganho" ? "Ganho" : stage === "Fechado — perdido" ? "Perda" : "Etapa", description: `Etapa alterada para ${stage}.` }); }
export async function deleteOpportunityRecord({ id, empresaId }) { const { error } = await supabase.from("crm_oportunidades").delete().eq("id", id).eq("empresa_id", String(empresaId)); if (error) throw error; }
