const hoje = new Date();
const dataRelativa = (dias) => {
  const data = new Date(hoje);
  data.setDate(data.getDate() + dias);
  return data.toISOString().slice(0, 10);
};

export const CRM_DEMO_OPPORTUNITIES = [
  { id: 1, empresa: "Metalúrgica Horizonte", contatoPrincipal: "Carla Mendes", telefone: "(11) 3456-7810", whatsapp: "(11) 99821-4400", email: "carla@horizonte.demo", cidade: "Guarulhos", estado: "SP", segmento: "Metalúrgica", origemLead: "Indicação", vendedorResponsavel: "Marina Costa", produtoInteresse: "Tarugo de alumínio", valorEstimado: 148000, pesoEstimado: 12500, probabilidade: 70, etapa: "Negociação", prioridade: "Alta", proximoContato: dataRelativa(0), observacoes: "Cliente solicitou condição para compra recorrente.", motivoPerda: "", status: "Ativa", atividades: [{ id: 11, tipo: "Reunião", data: dataRelativa(-2), descricao: "Apresentação da proposta comercial." }] },
  { id: 2, empresa: "Fundição Vale Verde", contatoPrincipal: "Rafael Lima", telefone: "(31) 3222-9080", whatsapp: "(31) 99114-2208", email: "rafael@valeverde.demo", cidade: "Contagem", estado: "MG", segmento: "Fundição", origemLead: "Feira industrial", vendedorResponsavel: "Paulo Nunes", produtoInteresse: "Lingote e sucata", valorEstimado: 86500, pesoEstimado: 8900, probabilidade: 45, etapa: "Proposta enviada", prioridade: "Média", proximoContato: dataRelativa(-1), observacoes: "Aguardando avaliação técnica.", motivoPerda: "", status: "Ativa", atividades: [{ id: 21, tipo: "Proposta enviada", data: dataRelativa(-4), descricao: "Proposta enviada por e-mail." }] },
  { id: 3, empresa: "Alumitech Componentes", contatoPrincipal: "Bruno Reis", telefone: "(19) 3111-5480", whatsapp: "(19) 99710-5521", email: "bruno@alumitech.demo", cidade: "Campinas", estado: "SP", segmento: "Autopeças", origemLead: "Site", vendedorResponsavel: "Marina Costa", produtoInteresse: "Perfil industrial", valorEstimado: 220000, pesoEstimado: 17400, probabilidade: 90, etapa: "Fechado — ganho", prioridade: "Alta", proximoContato: dataRelativa(5), observacoes: "Negócio aprovado para fornecimento trimestral.", motivoPerda: "", status: "Concluída", atividades: [{ id: 31, tipo: "Ligação", data: dataRelativa(-7), descricao: "Confirmação do pedido." }] },
  { id: 4, empresa: "Estruturas São Lucas", contatoPrincipal: "Aline Castro", telefone: "(41) 3330-7070", whatsapp: "(41) 99280-1103", email: "aline@saolucas.demo", cidade: "Curitiba", estado: "PR", segmento: "Construção", origemLead: "Prospecção ativa", vendedorResponsavel: "Diego Alves", produtoInteresse: "Perfil e chapa", valorEstimado: 64000, pesoEstimado: 5100, probabilidade: 25, etapa: "Qualificação", prioridade: "Baixa", proximoContato: dataRelativa(1), observacoes: "Validar especificações e volume mensal.", motivoPerda: "", status: "Ativa", atividades: [] },
  { id: 5, empresa: "Recicla Sul Metais", contatoPrincipal: "Fernanda Luz", telefone: "(51) 3020-8181", whatsapp: "(51) 99912-7302", email: "fernanda@reciclasul.demo", cidade: "Canoas", estado: "RS", segmento: "Reciclagem", origemLead: "Carteira antiga", vendedorResponsavel: "Paulo Nunes", produtoInteresse: "Sucata de alumínio", valorEstimado: 42500, pesoEstimado: 7200, probabilidade: 10, etapa: "Fechado — perdido", prioridade: "Média", proximoContato: dataRelativa(-8), observacoes: "Cliente optou por fornecedor regional.", motivoPerda: "Preço e logística", status: "Encerrada", atividades: [] },
  { id: 6, empresa: "Indústria Nova Era", contatoPrincipal: "Lucas Prado", telefone: "(15) 3201-9090", whatsapp: "(15) 99661-4220", email: "lucas@novaera.demo", cidade: "Sorocaba", estado: "SP", segmento: "Industrial", origemLead: "LinkedIn", vendedorResponsavel: "Diego Alves", produtoInteresse: "Tarugo liga 6061", valorEstimado: 110000, pesoEstimado: 9300, probabilidade: 20, etapa: "Novo contato", prioridade: "Alta", proximoContato: dataRelativa(0), observacoes: "Primeiro contato realizado.", motivoPerda: "", status: "Ativa", atividades: [{ id: 61, tipo: "WhatsApp", data: dataRelativa(0), descricao: "Mensagem inicial enviada." }] },
];

export function createCrmDemoData() {
  return CRM_DEMO_OPPORTUNITIES.map((item) => ({ ...item, atividades: item.atividades.map((activity) => ({ ...activity })) }));
}
