import { supabase } from "../../../supabase";

export function fromDatabase(item) {
  return { id: item.id, clienteId: item.cliente_id, contatoPrincipal: item.cliente_nome || "", empresa: item.empresa_cliente || "", telefone: item.telefone || "", whatsapp: item.whatsapp || "", email: item.email || "", cidade: item.cidade || "", estado: item.estado || "", pais: item.pais || "", origemLead: item.origem || "", segmento: item.segmento || "", produtoInteresse: item.produto_material || "", quantidade: item.quantidade ?? "", unidade: item.unidade || "kg", valorEstimado: Number(item.valor_estimado || 0), probabilidade: Number(item.probabilidade || 0), etapa: item.etapa, prioridade: item.prioridade, vendedorResponsavel: item.responsavel || "", proximoContato: item.previsao_fechamento || "", observacoes: item.observacoes || "", motivoPerda: item.motivo_perda || "", createdAt: item.created_at, updatedAt: item.updated_at, atividades: (item.crm_oportunidade_historico || []).map((entry) => ({ id: entry.id, tipo: entry.tipo, descricao: entry.descricao, data: String(entry.created_at).slice(0, 10) })) };
}
function opportunityPayload(item, empresaId) { return { empresa_id: String(empresaId), cliente_id: item.clienteId ? String(item.clienteId) : null, cliente_nome: item.contatoPrincipal || null, empresa_cliente: item.empresa, telefone: item.telefone || null, whatsapp: item.whatsapp || null, email: item.email || null, cidade: item.cidade || null, estado: item.estado || null, pais: item.pais || null, origem: item.origemLead || null, segmento: item.segmento || null, produto_material: item.produtoInteresse || null, quantidade: item.quantidade === "" ? null : Number(item.quantidade), unidade: item.unidade || null, valor_estimado: Number(item.valorEstimado || 0), probabilidade: Number(item.probabilidade || 0), etapa: item.etapa, prioridade: item.prioridade, responsavel: item.vendedorResponsavel || null, previsao_fechamento: item.proximoContato || null, observacoes: item.observacoes || null, motivo_perda: item.motivoPerda || null }; }
export async function listOpportunities(empresaId) { const { data, error } = await supabase.from("crm_oportunidades").select("*, crm_oportunidade_historico(id,tipo,descricao,created_at)").eq("empresa_id", String(empresaId)).order("created_at", { ascending: false }); if (error) throw error; return (data || []).map(fromDatabase); }
export async function addOpportunityHistory({ opportunityId, empresaId, userId, type, description }) { const { error } = await supabase.from("crm_oportunidade_historico").insert({ oportunidade_id: opportunityId, empresa_id: String(empresaId), user_id: userId, tipo: type, descricao: description }); if (error) throw error; }
async function recordHistoryBestEffort(args) { try { await addOpportunityHistory(args); return null; } catch (error) { console.error("Oportunidade salva, mas o histórico não foi registrado:", error); return error; } }
export async function saveOpportunityRecord({ opportunity, empresaId, userId }) { const payload = opportunityPayload(opportunity, empresaId); const query = opportunity.id ? supabase.from("crm_oportunidades").update(payload).eq("id", opportunity.id).eq("empresa_id", String(empresaId)) : supabase.from("crm_oportunidades").insert({ ...payload, user_id: userId }); const { data, error } = await query.select("*").single(); if (error) throw error; const historyError = await recordHistoryBestEffort({ opportunityId: data.id, empresaId, userId, type: opportunity.id ? "Edição" : "Criação", description: opportunity.id ? "Oportunidade atualizada após confirmação humana." : "Oportunidade criada após confirmação humana." }); return { ...fromDatabase(data), historyWarning: historyError ? "Oportunidade salva sem registro no histórico." : "" }; }
export async function updateOpportunityStage({ id, stage, empresaId, userId }) { const { error } = await supabase.from("crm_oportunidades").update({ etapa: stage }).eq("id", id).eq("empresa_id", String(empresaId)); if (error) throw error; return recordHistoryBestEffort({ opportunityId: id, empresaId, userId, type: stage === "Fechado — ganho" ? "Ganho" : stage === "Fechado — perdido" ? "Perda" : "Etapa", description: `Etapa alterada para ${stage}.` }); }
export async function deleteOpportunityRecord({ id, empresaId }) { const { error } = await supabase.from("crm_oportunidades").delete().eq("id", id).eq("empresa_id", String(empresaId)); if (error) throw error; }
