import { useEffect, useMemo, useState } from "react";
import { EmptyState, FeedbackBanner, LoadingState, MetricGrid, ModuleHeader, OperationModal } from "../../../components/operations/OperationsUI";
import useFinanceiroCorporativo from "../hooks/useFinanceiroCorporativo";
import { budgetToTitle, purchaseToTitle, registerTitle, reverseSettlement, saleToTitle, saveReconciliation, settleTitle } from "../services/financeiro.service";
import "../financeiro-corporativo.css";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = (value) => { const parsed = new Date(`${String(value || "").slice(0, 10)}T12:00:00`); return value && !Number.isNaN(parsed.getTime()) ? parsed.toLocaleDateString("pt-BR") : "Data não informada"; };
const today = () => { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
const number = (value) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
const dateTime = (value) => { const parsed = new Date(value); return value && !Number.isNaN(parsed.getTime()) ? parsed.toLocaleString("pt-BR") : "Data não informada"; };
const emptyTitle = (type = "Pagar") => ({ type, party: "", origin: "Manual", reference: "", description: "", category: "", costCenter: "", dueDate: today(), value: "", notes: "" });

function PeriodFilter({ finance }) {
  return <section className="corp-fin-period"><div>{[["today","Hoje"],["7","7 dias"],["30","30 dias"],["month","Mês atual"],["year","Ano atual"],["custom","Personalizado"]].map(([value, label]) => <button key={value} className={finance.period === value ? "active" : ""} onClick={() => finance.setPeriod(value)}>{label}</button>)}</div>{finance.period === "custom" && <div className="corp-fin-period__custom"><input type="date" value={finance.customStart} onChange={(event) => finance.setCustomStart(event.target.value)} aria-label="Período inicial"/><input type="date" value={finance.customEnd} onChange={(event) => finance.setCustomEnd(event.target.value)} aria-label="Período final"/></div>}</section>;
}

function TitlesTable({ items, onEdit, onSettle }) {
  if (!items.length) return <EmptyState title="Nenhum título encontrado" description="Cadastre manualmente ou confirme uma integração pendente."/>;
  return <div className="ops-table-wrap"><table className="ops-table corp-fin-table"><thead><tr><th>Vencimento</th><th>Tipo / origem</th><th>Contraparte</th><th>Descrição</th><th>Valor</th><th>Baixado</th><th>Saldo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={item.saldo > 0 && item.vencimento < today() ? "overdue" : ""}><td>{date(item.vencimento)}</td><td><strong>{item.tipo}</strong><small>{item.origem}{item.referencia ? ` · ${item.referencia}` : ""}</small></td><td>{item.contraparte_nome}</td><td><strong>{item.descricao}</strong><small>{[item.categoria,item.centro_custo].filter(Boolean).join(" · ")}</small></td><td>{money.format(item.valor_original)}</td><td>{money.format(item.valor_baixado)}</td><td><strong>{money.format(item.saldo)}</strong></td><td><span className={`corp-fin-status status-${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="corp-fin-table-actions"><button className="corp-fin-inline" onClick={() => onEdit(item)}>Editar</button>{item.saldo > 0 && item.status !== "Cancelado" && <button className="corp-fin-inline" onClick={() => onSettle(item)}>Baixar</button>}</div></td></tr>)}</tbody></table></div>;
}

function IntegrationCard({ eyebrow, title, detail, value, disabled, onConfirm }) {
  return <article className="corp-fin-integration"><div><small>{eyebrow}</small><strong>{title}</strong><span>{detail}</span></div><b>{money.format(value || 0)}</b><button disabled={disabled} onClick={onConfirm}>{disabled ? "Já integrado" : "Revisar e confirmar"}</button></article>;
}

export default function FinanceiroCorporativoPage({ empresaId, userId, initialTab = "overview" }) {
  const finance = useFinanceiroCorporativo(empresaId);
  const [tab, setTab] = useState(initialTab); const [feedback, setFeedback] = useState(null); const [busy, setBusy] = useState(false);
  const [titleForm, setTitleForm] = useState(null); const [settlementTitle, setSettlementTitle] = useState(null);
  const [settlement, setSettlement] = useState({ value: "", date: today(), method: "PIX", account: "", notes: "" });
  const [reconciliation, setReconciliation] = useState(null);
  useEffect(() => setTab(initialTab), [initialTab]);
  const originKeys = useMemo(() => new Set(finance.titles.map((item) => `${item.origem}:${item.origem_id}`)), [finance.titles]);
  const run = async (work, message) => { setBusy(true); setFeedback(null); try { await work(); setFeedback({ type: "success", message }); await finance.refresh(); return true; } catch (cause) { setFeedback({ type: "error", message: cause.message || "Não foi possível concluir a operação." }); return false; } finally { setBusy(false); } };
  const openSettlement = (item) => { setSettlementTitle(item); setSettlement({ value: String(item.saldo), date: today(), method: "PIX", account: "", notes: "" }); };
  const openEdit = (item) => setTitleForm({ id:item.id,type:item.tipo,party:item.contraparte_nome,origin:item.origem,reference:item.referencia||"",description:item.descricao,category:item.categoria||"",costCenter:item.centro_custo||"",dueDate:item.vencimento,value:item.valor_original,notes:item.observacoes||"" });
  const confirmSource = async (title, sourceLabel) => { if (!window.confirm(`Confirma a criação do título a partir de ${sourceLabel}? O processo não é automático.`)) return; await run(() => registerTitle({ empresaId, title }), "Título criado após confirmação humana."); };

  const metrics = [
    { label: "Contas a pagar", value: money.format(finance.payableBalance), detail: `${finance.payable.filter((item) => item.saldo > 0).length} título(s) em aberto`, icon: "↘", tone: "rose" },
    { label: "Contas a receber", value: money.format(finance.receivableBalance), detail: `${finance.receivable.filter((item) => item.saldo > 0).length} título(s) em aberto`, icon: "↗", tone: "green" },
    { label: "Vencido", value: money.format(finance.overdue.reduce((sum, item) => sum + number(item.saldo), 0)), detail: `${finance.overdue.length} compromisso(s)`, icon: "!", tone: "rose" },
    { label: "Fluxo realizado", value: money.format(finance.realized), detail: `Entradas ${money.format(finance.received)} · saídas ${money.format(finance.paid)}`, icon: "$", tone: finance.realized >= 0 ? "green" : "rose" },
    { label: "Saldo projetado", value: money.format(finance.projected), detail: `${finance.dueSoon.length} vencimento(s) em 7 dias`, icon: "◇", tone: finance.projected >= 0 ? "green" : "amber" },
  ];
  const tabTitles = tab === "payable" ? finance.payable : tab === "receivable" ? finance.receivable : finance.periodTitles;

  return <main className="ops-page corp-fin-page">
    <ModuleHeader eyebrow="Núcleo financeiro empresarial" title="Financeiro Corporativo" description="Títulos, baixas, projeção e conciliação com rastreabilidade multiempresa." actionLabel="Novo título" onAction={() => setTitleForm(emptyTitle(tab === "receivable" ? "Receber" : "Pagar"))}/>
    <FeedbackBanner feedback={feedback} onClose={() => setFeedback(null)}/>
    <MetricGrid items={metrics}/><PeriodFilter finance={finance}/>
    <nav className="corp-fin-tabs" aria-label="Seções do financeiro">{[["overview","Visão geral"],["payable","Contas a pagar"],["receivable","Contas a receber"],["forecast","Fluxo e previsão"],["integrations","Integrações"],["reconciliation","Conciliação"],["history","Histórico"]].map(([value,label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}</button>)}</nav>
    {finance.error && <div className="corp-fin-schema-warning"><strong>Financeiro temporariamente indisponível</strong><span>{finance.error}</span><small>Os dados existentes não foram alterados. Tente atualizar novamente.</small></div>}
    {finance.loading ? <LoadingState/> : <>
      {["overview","payable","receivable"].includes(tab) && <section className="ops-panel"><div className="ops-panel__header"><h2>{tab === "payable" ? "Contas a pagar" : tab === "receivable" ? "Contas a receber" : "Títulos do período"}</h2><span>{tabTitles.length} registro(s)</span></div><TitlesTable items={tabTitles} onEdit={openEdit} onSettle={openSettlement}/></section>}
      {tab === "forecast" && <section className="corp-fin-flow"><article><small>Saldo inicial do recorte</small><strong>Não disponível</strong><span>Sem conta bancária externa nesta fase</span></article><article><small>Entradas realizadas</small><strong>{money.format(finance.received)}</strong><span>Baixas de contas a receber</span></article><article><small>Saídas realizadas</small><strong>{money.format(finance.paid)}</strong><span>Baixas de contas a pagar</span></article><article><small>Saldo final realizado</small><strong>{money.format(finance.realized)}</strong><span>Entradas menos saídas</span></article><article><small>A receber futuro</small><strong>{money.format(finance.receivableBalance)}</strong><span>Saldo aberto real</span></article><article><small>A pagar futuro</small><strong>{money.format(finance.payableBalance)}</strong><span>Saldo aberto real</span></article><article className="featured"><small>Saldo projetado</small><strong>{money.format(finance.projected)}</strong><span>Recebíveis menos compromissos</span></article><article><small>Inadimplência</small><strong>{money.format(finance.overdue.filter((item) => item.tipo === "Receber").reduce((sum,item) => sum + number(item.saldo),0))}</strong><span>Recebíveis vencidos</span></article></section>}
      {tab === "integrations" && <section className="corp-fin-integrations"><header><h2>Revisão humana de origens</h2><span>Nada é convertido automaticamente.</span></header>{finance.unavailable.purchases && <p>Compras indisponível: {finance.unavailable.purchases}</p>}{finance.purchaseInstallments.map((item) => <IntegrationCard key={`p-${item.id}`} eyebrow="Compra · parcela preparada" title={`${item.pedidos_compra?.numero || "Pedido"} · parcela ${item.numero}`} detail={`Vence em ${date(item.vencimento)} · ${item.pedidos_compra?.fornecedor_snapshot?.nome || "Fornecedor"}`} value={item.valor} disabled={originKeys.has(`Compra:parcela:${item.id}`)} onConfirm={() => confirmSource(purchaseToTitle(item), `a parcela ${item.numero} do pedido ${item.pedidos_compra?.numero || "selecionado"}`)}/>)}{finance.sales.map((item) => <IntegrationCard key={`v-${item.id}`} eyebrow="Venda confirmada" title={`${item.cliente_nome || "Cliente"} · ${item.produto || "Venda"}`} detail={`Registrada em ${date(item.data_venda)}. O vencimento será revisado antes da confirmação.`} value={item.valor} disabled={originKeys.has(`Venda:${item.id}`)} onConfirm={() => { const due = window.prompt("Vencimento da conta a receber (AAAA-MM-DD):", today()); if (due) confirmSource(saleToTitle(item,due), `a venda ${item.id}`); }}/>)}{finance.budgets.map((item) => <IntegrationCard key={`o-${item.id}`} eyebrow="Orçamento aprovado" title={`${item.numero} · ${item.cliente_snapshot?.nome || "Cliente"}`} detail="Aprovação comercial disponível para geração financeira revisada." value={item.valor_final} disabled={originKeys.has(`Orçamento:${item.id}`)} onConfirm={() => { const due = window.prompt("Vencimento da conta a receber (AAAA-MM-DD):", item.validade || today()); if (due) confirmSource(budgetToTitle(item,due), `o orçamento ${item.numero}`); }}/>)}{!finance.purchaseInstallments.length && !finance.sales.length && !finance.budgets.length && <EmptyState/>}</section>}
      {tab === "reconciliation" && <section className="ops-panel"><div className="ops-panel__header"><h2>Conciliação manual</h2><button className="corp-fin-inline" onClick={() => setReconciliation({ titleId: finance.titles[0]?.id || "", account: "", date: today(), value: "", status: "Pendente", notes: "" })} disabled={!finance.titles.length}>Nova conciliação</button></div>{!finance.reconciliations.length ? <EmptyState title="Nenhuma conciliação" description="Associe manualmente um título a uma conta financeira."/> : <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Data</th><th>Conta</th><th>Valor</th><th>Status</th><th>Observações</th></tr></thead><tbody>{finance.reconciliations.map((item) => <tr key={item.id}><td>{date(item.data_movimento)}</td><td>{item.conta}</td><td>{money.format(item.valor)}</td><td>{item.status}</td><td>{item.observacoes || "—"}</td></tr>)}</tbody></table></div>}</section>}
      {tab === "history" && <section className="ops-panel"><div className="ops-panel__header"><h2>Histórico auditável</h2><span>Eventos imutáveis</span></div>{!finance.history.length ? <EmptyState/> : <div className="corp-fin-history">{finance.history.map((item) => <article key={item.id}><span>{item.tipo}</span><div><strong>{item.descricao}</strong><small>{dateTime(item.created_at)} · usuário {item.user_id ? String(item.user_id).slice(0,8) : "não informado"}</small></div></article>)}</div>}</section>}
    </>}
    {titleForm && <OperationModal title={`Nova conta a ${titleForm.type === "Pagar" ? "pagar" : "receber"}`} onClose={() => setTitleForm(null)} onSubmit={async () => { const ok = await run(() => registerTitle({ empresaId, title: titleForm }), "Título financeiro criado e registrado no histórico."); if(ok)setTitleForm(null); }} submitLabel="Confirmar título" disabled={busy || !titleForm.party || !titleForm.description || !titleForm.value}><label className="ops-field"><span>Tipo</span><select value={titleForm.type} onChange={(event) => setTitleForm({...titleForm,type:event.target.value})}><option>Pagar</option><option>Receber</option></select></label><label className="ops-field"><span>Origem</span><select value={titleForm.origin} onChange={(event) => setTitleForm({...titleForm,origin:event.target.value})}>{["Manual","Despesa","Imposto","Serviço","Outro"].map((item)=><option key={item}>{item}</option>)}</select></label><label className="ops-field"><span>Fornecedor / cliente</span><input value={titleForm.party} onChange={(event)=>setTitleForm({...titleForm,party:event.target.value})}/></label><label className="ops-field"><span>Referência</span><input value={titleForm.reference} onChange={(event)=>setTitleForm({...titleForm,reference:event.target.value})}/></label><label className="ops-field ops-field--wide"><span>Descrição</span><input value={titleForm.description} onChange={(event)=>setTitleForm({...titleForm,description:event.target.value})}/></label><label className="ops-field"><span>Categoria</span><input value={titleForm.category} onChange={(event)=>setTitleForm({...titleForm,category:event.target.value})}/></label><label className="ops-field"><span>Centro de custo</span><input value={titleForm.costCenter} onChange={(event)=>setTitleForm({...titleForm,costCenter:event.target.value})}/></label><label className="ops-field"><span>Vencimento</span><input type="date" value={titleForm.dueDate} onChange={(event)=>setTitleForm({...titleForm,dueDate:event.target.value})}/></label><label className="ops-field"><span>Valor</span><input type="number" min="0.01" step="0.01" value={titleForm.value} onChange={(event)=>setTitleForm({...titleForm,value:event.target.value})}/></label></OperationModal>}
    {settlementTitle && <OperationModal title={`Baixa · ${settlementTitle.descricao}`} onClose={() => setSettlementTitle(null)} onSubmit={async () => { const ok=await run(()=>settleTitle({empresaId,titleId:settlementTitle.id,settlement}),"Baixa registrada sem apagar o histórico.");if(ok)setSettlementTitle(null);}} submitLabel="Confirmar baixa" disabled={busy || !settlement.value || Number(settlement.value)>Number(settlementTitle.saldo)}><div className="ops-preview">Saldo disponível: <strong>{money.format(settlementTitle.saldo)}</strong>. A baixa pode ser parcial ou total.</div><label className="ops-field"><span>Valor</span><input type="number" min="0.01" max={settlementTitle.saldo} step="0.01" value={settlement.value} onChange={(event)=>setSettlement({...settlement,value:event.target.value})}/></label><label className="ops-field"><span>Data</span><input type="date" value={settlement.date} onChange={(event)=>setSettlement({...settlement,date:event.target.value})}/></label><label className="ops-field"><span>Forma</span><input value={settlement.method} onChange={(event)=>setSettlement({...settlement,method:event.target.value})}/></label><label className="ops-field"><span>Conta</span><input value={settlement.account} onChange={(event)=>setSettlement({...settlement,account:event.target.value})}/></label></OperationModal>}
    {reconciliation && <OperationModal title="Nova conciliação manual" onClose={()=>setReconciliation(null)} onSubmit={async()=>{const ok=await run(()=>saveReconciliation({empresaId,userId,reconciliation}),"Conciliação registrada.");if(ok)setReconciliation(null);}} submitLabel="Salvar conciliação" disabled={busy||!reconciliation.titleId||!reconciliation.account||!reconciliation.value}><label className="ops-field ops-field--wide"><span>Título</span><select value={reconciliation.titleId} onChange={(event)=>setReconciliation({...reconciliation,titleId:event.target.value})}>{finance.titles.map((item)=><option key={item.id} value={item.id}>{item.descricao} · {money.format(item.valor_original)}</option>)}</select></label><label className="ops-field"><span>Conta financeira</span><input value={reconciliation.account} onChange={(event)=>setReconciliation({...reconciliation,account:event.target.value})}/></label><label className="ops-field"><span>Data</span><input type="date" value={reconciliation.date} onChange={(event)=>setReconciliation({...reconciliation,date:event.target.value})}/></label><label className="ops-field"><span>Valor</span><input type="number" min="0.01" step="0.01" value={reconciliation.value} onChange={(event)=>setReconciliation({...reconciliation,value:event.target.value})}/></label><label className="ops-field"><span>Status</span><select value={reconciliation.status} onChange={(event)=>setReconciliation({...reconciliation,status:event.target.value})}><option>Pendente</option><option>Conciliado</option><option>Divergente</option></select></label></OperationModal>}
    {tab === "history" && finance.settlements.filter((item)=>item.tipo==="Baixa"&&!finance.settlements.some((other)=>other.estorno_de===item.id)).length>0 && <section className="corp-fin-reversals"><h3>Reversão segura</h3>{finance.settlements.filter((item)=>item.tipo==="Baixa"&&!finance.settlements.some((other)=>other.estorno_de===item.id)).slice(0,10).map((item)=><button key={item.id} disabled={busy} onClick={()=>{if(window.confirm(`Estornar a baixa de ${money.format(item.valor)}? O evento original será preservado.`))run(()=>reverseSettlement({empresaId,settlementId:item.id,notes:"Estorno confirmado pelo usuário."}),"Estorno registrado sem exclusão física.");}}>Estornar {money.format(item.valor)} de {date(item.data_movimento)}</button>)}</section>}
  </main>;
}
