import { useState } from "react";
import { OperationModal } from "../../../components/operations/OperationsUI";
import { CATALOGO_IMPORT_TYPES } from "../constants/catalogo.constants";
import { createImportDraft } from "../services/catalogoImportDraft.service";

export default function CatalogImportModal({ companyId, userId, onClose, onSave }) {
  const [form, setForm] = useState({ supplier: "WZM", customSupplier: "", catalogName: "", catalogVersion: "", type: CATALOGO_IMPORT_TYPES.PDF, totalPages: "", notes: "", file: null }); const [error, setError] = useState("");
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  function submit() { const supplierName = form.supplier === "Outro" ? form.customSupplier.trim() : form.supplier; if (!companyId || !userId) return setError("Sessão incompleta: empresa e usuário são obrigatórios."); if (!supplierName) return setError("Informe o fornecedor."); const draft = createImportDraft({ companyId, userId, supplierName, catalogName: form.catalogName.trim() || null, catalogVersion: form.catalogVersion.trim() || null, originalFileName: form.file?.name || null, type: form.type, totalPages: form.totalPages ? Number(form.totalPages) : null }); onSave({ ...draft, notes: form.notes.trim(), fileMetadata: form.file ? { name: form.file.name, size: form.file.size, type: form.file.type } : null }); }
  return <OperationModal title="Importar catálogo" onClose={onClose} onSubmit={submit} submitLabel="Criar rascunho" disabled={!companyId || !userId}>
    {error && <div className="ops-preview catalog-import-error">{error}</div>}<label className="ops-field"><span>Fornecedor</span><select value={form.supplier} onChange={(e) => update("supplier", e.target.value)}><option>WZM</option><option>BGB</option><option>Outro</option></select></label>{form.supplier === "Outro" && <label className="ops-field"><span>Outro fornecedor</span><input value={form.customSupplier} onChange={(e) => update("customSupplier", e.target.value)} /></label>}<label className="ops-field"><span>Nome do catálogo</span><input value={form.catalogName} onChange={(e) => update("catalogName", e.target.value)} /></label><label className="ops-field"><span>Versão</span><input value={form.catalogVersion} onChange={(e) => update("catalogVersion", e.target.value)} /></label><label className="ops-field"><span>Tipo de importação</span><select value={form.type} onChange={(e) => update("type", e.target.value)}>{Object.entries(CATALOGO_IMPORT_TYPES).map(([key, value]) => <option key={value} value={value}>{key}</option>)}</select></label><label className="ops-field"><span>Arquivo local</span><input type="file" accept=".pdf,.xlsx,.xls,.csv" onChange={(e) => update("file", e.target.files?.[0] || null)} /></label><label className="ops-field"><span>Total de páginas</span><input type="number" min="1" value={form.totalPages} onChange={(e) => update("totalPages", e.target.value)} /></label><label className="ops-field ops-field--wide"><span>Observações</span><textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label>{form.file && <div className="ops-preview">Somente metadados: {form.file.name} · {(form.file.size / 1024).toFixed(1)} KB · {form.file.type || "tipo não informado"}</div>}
  </OperationModal>;
}
