import { useState } from "react";
import { DUPLICATE_ACTIONS, EXTRACTION_CONFIDENCE } from "../constants/catalogo.constants";
import CatalogProductEditModal from "./CatalogProductEditModal";

const confidenceLabel = { [EXTRACTION_CONFIDENCE.HIGH]: "Alta", [EXTRACTION_CONFIDENCE.MEDIUM]: "Média", [EXTRACTION_CONFIDENCE.LOW]: "Baixa", [EXTRACTION_CONFIDENCE.NOT_FOUND]: "Não encontrado" };
const formatDate = (value) => value ? new Date(value).toLocaleString("pt-BR") : "—";
export default function CatalogImportReview({ draft, summary, onBack, onEditProduct, onDetectDuplicates, onLoadDemo, onMarkReview }) {
  const [editing, setEditing] = useState(null);
  const change = (product, changes) => onEditProduct(product.id, changes);
  return <section className="catalog-import-review"><header className="catalog-review-header"><div><button onClick={onBack}>← Histórico</button><p className="catalog-eyebrow">Conferência da importação</p><h2>{draft.catalogName || "Catálogo sem nome"}</h2><span>{draft.supplierName} · {draft.catalogVersion || "sem versão"}</span></div><div><button className="catalog-demo-action" onClick={onLoadDemo}>Carregar demonstração WZM</button><button onClick={onDetectDuplicates}>Detectar duplicidades</button><button onClick={onMarkReview}>Marcar em revisão</button></div></header>
    <div className="catalog-review-meta">{[["Arquivo", draft.originalFileName], ["Status", draft.status], ["Data", formatDate(draft.createdAt)], ["Produtos", draft.products.length], ["Alertas", summary.withWarnings], ["Duplicidades", summary.duplicates]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value ?? "—"}</strong></div>)}</div>
    <div className="catalog-import-summary">{[["Total", summary.total], ["Selecionados", summary.selected], ["Ignorados", summary.ignored], ["Com alertas", summary.withWarnings], ["Duplicidades", summary.duplicates], ["Prontos para revisão", summary.readyForReview]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
    {!draft.products.length ? <div className="catalog-import-empty"><strong>Conferência vazia</strong><span>Adicione itens manualmente em uma etapa futura ou carregue a demonstração WZM para validar esta interface.</span></div> : <div className="catalog-import-table-wrap"><table className="catalog-import-table"><thead><tr><th>Sel.</th><th>Código</th><th>Descrição</th><th>Categoria</th><th>Medidas</th><th>Peso</th><th>Página</th><th>Confiança</th><th>Duplicidade</th><th>Alertas</th><th>Ações</th></tr></thead><tbody>{draft.products.map((product) => { const confidence = product.confidence?.description?.confidence || EXTRACTION_CONFIDENCE.NOT_FOUND; return <tr key={product.id} className={product.duplicateOf ? "is-duplicate" : ""}><td><input type="checkbox" checked={product.selected} onChange={(e) => change(product, { selected: e.target.checked })} /></td><td><strong>{product.supplierCode || "—"}</strong></td><td>{product.description || product.name || "—"}</td><td>{product.category || "—"}</td><td>{product.technical?.dimensions?.originalText || "—"}</td><td>{product.technical?.weightPerMeter ?? "—"} kg/m</td><td>{product.source?.page || "—"}</td><td><span className={`catalog-confidence catalog-confidence--${confidence}`}>{confidenceLabel[confidence]}</span></td><td><select value={product.duplicateAction} onChange={(e) => change(product, { duplicateAction: e.target.value })}>{Object.values(DUPLICATE_ACTIONS).map((value) => <option key={value}>{value}</option>)}</select>{product.duplicateOf && <small>Possível duplicidade</small>}</td><td>{product.warnings?.length ? <span className="catalog-warning">{product.warnings.length}</span> : "—"}</td><td><div className="catalog-item-actions"><button onClick={() => setEditing(product)}>Editar</button><button onClick={() => change(product, { selected: false, duplicateAction: DUPLICATE_ACTIONS.IGNORE })}>Ignorar</button><button onClick={() => change(product, { selected: true, duplicateAction: DUPLICATE_ACTIONS.CREATE })}>Criar</button><button onClick={() => change(product, { duplicateAction: DUPLICATE_ACTIONS.REVIEW })}>Revisar</button></div></td></tr>; })}</tbody></table></div>}
    {editing && <CatalogProductEditModal product={editing} onClose={() => setEditing(null)} onSave={(product) => { onEditProduct(product.id, product); setEditing(null); }} />}
  </section>;
}
