import { supabase } from "../../../supabase";
export const MOVEMENT_TYPES=["Entrada","Saída","Transferência","Reserva","Liberação","Ajuste","Inventário","Reversão"];
const number=(value)=>Number(value||0);
export function mapStock(row){return{id:row.id,empresaId:row.empresa_id,produtoId:row.produto_id,codigo:row.codigo,descricao:row.descricao,categoria:row.categoria||"",liga:row.liga||"",tempera:row.tempera||"",dimensao:row.dimensao||"",pesoUnitario:number(row.peso_unitario),unidade:row.unidade,estoqueAtual:number(row.estoque_atual),estoqueReservado:number(row.estoque_reservado),estoqueDisponivel:number(row.estoque_disponivel),estoqueMinimo:number(row.estoque_minimo),estoqueMaximo:row.estoque_maximo===null?null:number(row.estoque_maximo),pontoReposicao:number(row.ponto_reposicao),localizacao:row.localizacao||"",observacoes:row.observacoes||"",custoUnitario:number(row.custo_unitario),prazoReposicaoDias:number(row.prazo_reposicao_dias),ultimaMovimentacaoEm:row.ultima_movimentacao_em,createdAt:row.created_at,updatedAt:row.updated_at}}
export async function listStock(empresaId){const{data,error}=await supabase.from("estoque").select("*").eq("empresa_id",String(empresaId)).order("descricao");if(error)throw error;return(data||[]).map(mapStock)}
export async function listMovements(empresaId){const{data,error}=await supabase.from("estoque_movimentacoes").select("*").eq("empresa_id",String(empresaId)).order("created_at",{ascending:false}).limit(500);if(error)throw error;return data||[]}
export async function saveStockItem({empresaId,item}){const payload={empresa_id:String(empresaId),produto_id:item.produtoId?String(item.produtoId):null,codigo:String(item.codigo||"").trim(),descricao:String(item.descricao||"").trim(),categoria:item.categoria||null,liga:item.liga||null,tempera:item.tempera||null,dimensao:item.dimensao||null,peso_unitario:number(item.pesoUnitario),unidade:item.unidade||"kg",estoque_minimo:number(item.estoqueMinimo),estoque_maximo:item.estoqueMaximo===""||item.estoqueMaximo==null?null:number(item.estoqueMaximo),ponto_reposicao:number(item.pontoReposicao),localizacao:item.localizacao||null,observacoes:item.observacoes||null,custo_unitario:number(item.custoUnitario),prazo_reposicao_dias:number(item.prazoReposicaoDias),updated_at:new Date().toISOString()};if(!payload.codigo||!payload.descricao)throw new Error("Código e descrição são obrigatórios.");const query=item.id?supabase.from("estoque").update(payload).eq("id",item.id).eq("empresa_id",String(empresaId)):supabase.from("estoque").insert(payload);const{data,error}=await query.select("*").single();if(error)throw error;return mapStock(data)}
export async function moveStock({empresaId,stockId,type,quantity,origin="Manual",originId,notes,destination,reversalId}){const{data,error}=await supabase.rpc("movimentar_estoque",{p_estoque_id:stockId,p_empresa_id:String(empresaId),p_tipo:type,p_quantidade:number(quantity),p_origem:origin,p_origem_id:originId||null,p_observacoes:notes||null,p_localizacao_destino:destination||null,p_reversao_de:reversalId||null});if(error)throw error;return mapStock(data)}
export const reserveQuoteItem=(args)=>moveStock({...args,type:"Reserva",origin:"Orçamento"});export const releaseQuoteReservation=(args)=>moveStock({...args,type:"Liberação",origin:"Orçamento"});export const receivePurchase=(args)=>moveStock({...args,type:"Entrada",origin:"Compra"});export const dispatchSale=(args)=>moveStock({...args,type:"Saída",origin:"Venda"});
export async function convertReservationToSale({empresaId,stockId,quantity,saleId,quoteId}){const{error}=await supabase.rpc("baixar_reserva_estoque",{p_estoque_id:stockId,p_empresa_id:String(empresaId),p_quantidade:number(quantity),p_venda_id:String(saleId),p_orcamento_id:String(quoteId)});if(error)throw error}
export async function createInventory({empresaId,userId,stock,notes}){const numero=`INV-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const{data,error}=await supabase.from("inventarios").insert({empresa_id:String(empresaId),user_id:userId,numero,observacoes:notes||null}).select("*").single();if(error)throw error;if(stock.length){const{error:itemError}=await supabase.from("inventario_itens").insert(stock.map((item)=>({inventario_id:data.id,empresa_id:String(empresaId),estoque_id:item.id,quantidade_sistema:item.estoqueAtual})));if(itemError)throw itemError}return data}
export async function listInventories(empresaId){const{data,error}=await supabase.from("inventarios").select("*, inventario_itens(*)").eq("empresa_id",String(empresaId)).order("data_inicio",{ascending:false});if(error)throw error;return data||[]}
export async function countInventoryItem({empresaId,inventoryId,itemId,count,notes}){const{error}=await supabase.from("inventario_itens").update({quantidade_contada:number(count),observacoes:notes||null}).eq("id",itemId).eq("inventario_id",inventoryId).eq("empresa_id",String(empresaId));if(error)throw error}
export async function finishInventory({empresaId,inventory}){const{error}=await supabase.rpc("finalizar_inventario",{p_inventario_id:inventory.id,p_empresa_id:String(empresaId)});if(error)throw error}
export async function getStockAvailability(empresaId){return listStock(empresaId)}
