import{supabase}from"../../../supabase";
import{calculatePurchaseCommission}from"../../../services/commissionEngine";
export const PURCHASE_STATUSES=["Rascunho","Solicitado","Em cotação","Aprovado","Comprado","Recebido parcialmente","Recebido","Cancelado"];
const n=(v)=>Number(v||0);export function mapOrder(row){return{id:row.id,numero:row.numero,status:row.status,data:row.data,previsao:row.previsao,fornecedorId:row.fornecedor_id,fornecedor:row.fornecedor_snapshot||{},condicaoPagamento:row.condicao_pagamento||"",transportadora:row.transportadora||"",frete:n(row.frete),desconto:n(row.desconto),observacoes:row.observacoes||"",valorTotal:n(row.valor_total),createdAt:row.created_at,items:(row.pedido_compra_itens||[]).map((i)=>({id:i.id,produtoId:i.produto_id,estoqueId:i.estoque_id,codigo:i.produto,descricao:i.descricao||"",liga:i.liga||"",tempera:i.tempera||"",dimensao:i.dimensao||"",peso:n(i.peso),quantidade:n(i.quantidade),recebida:n(i.quantidade_recebida),unidade:i.unidade,valorUnitario:n(i.valor_unitario),subtotal:n(i.subtotal),comissao:n(i.comissao),dadosCatalogo:i.dados_catalogo||{}})),quotes:row.pedido_compra_cotacoes||[],history:row.pedido_compra_historico||[],installments:row.pedido_compra_parcelas||[]}}
export async function listOrders(empresaId){const{data,error}=await supabase.from("pedidos_compra").select("*,pedido_compra_itens(*),pedido_compra_cotacoes(*),pedido_compra_historico(*),pedido_compra_parcelas(*)").eq("empresa_id",String(empresaId)).order("created_at",{ascending:false});if(error)throw error;return(data||[]).map(mapOrder)}
export async function listLegacyPurchases(empresaId){const{data,error}=await supabase.from("compras").select("*").eq("empresa_id",empresaId).order("data_compra",{ascending:false}).order("id",{ascending:false});if(error)throw error;return(data||[]).map((row)=>({...row,source:"legacy",sourceLabel:"Compra histórica"}))}
export async function updateLegacyPurchase({empresaId,purchaseId,changes}){const payload={data_compra:changes.dataCompra,fornecedor:changes.fornecedor.trim(),produto:changes.produto.trim(),kilos:Number(changes.kilos),valor:Number(changes.valor)};const{data,error}=await supabase.from("compras").update(payload).eq("id",purchaseId).eq("empresa_id",empresaId).select("*").single();if(error)throw error;if(String(data.empresa_id)!==String(empresaId))throw new Error("A compra histórica não pertence à empresa atual.");return data}
export async function listSuppliers(userId){const{data,error}=await supabase.from("fornecedores").select("*").eq("user_id",userId).order("nome");if(error)throw error;return data||[]}
const totals=(order)=>{const subtotal=order.items.reduce((s,i)=>s+n(i.quantidade)*n(i.valorUnitario),0);return{subtotal,total:subtotal+n(order.frete)-n(order.desconto)}};
export async function saveOrder({empresaId,userId,order}){const supplier=order.supplier;const values=totals(order);const payload={empresa_id:String(empresaId),user_id:userId,fornecedor_id:String(supplier.id),fornecedor_snapshot:supplier,numero:order.numero||`PC-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`,status:order.status||"Rascunho",data:order.data,previsao:order.previsao||null,condicao_pagamento:order.condicaoPagamento||null,transportadora:order.transportadora||null,frete:n(order.frete),desconto:n(order.desconto),observacoes:order.observacoes||null,valor_total:values.total,updated_at:new Date().toISOString()};const query=order.id?supabase.from("pedidos_compra").update(payload).eq("id",order.id).eq("empresa_id",String(empresaId)):supabase.from("pedidos_compra").insert(payload);const{data,error}=await query.select("*").single();if(error)throw error;if(order.id){await addHistory({orderId:data.id,empresaId,userId,type:"Edição",description:"Pedido editado após confirmação."});return data.id}const itemRows=order.items.map((item)=>{const commission=calculatePurchaseCommission({product:item.descricao||item.codigo,quantity:item.peso||item.quantidade,unit:item.unidade}).commission;return{pedido_id:data.id,empresa_id:String(empresaId),produto_id:String(item.produtoId),estoque_id:item.estoqueId||null,produto:item.codigo||item.descricao,descricao:item.descricao||null,liga:item.liga||null,tempera:item.tempera||null,dimensao:item.dimensao||null,peso:n(item.peso),quantidade:n(item.quantidade),unidade:item.unidade||"kg",valor_unitario:n(item.valorUnitario),subtotal:n(item.quantidade)*n(item.valorUnitario),comissao:commission,dados_catalogo:item.dadosCatalogo||{}}});if(itemRows.length){const{error:itemError}=await supabase.from("pedido_compra_itens").insert(itemRows);if(itemError)throw itemError}await addHistory({orderId:data.id,empresaId,userId,type:"Criação",description:"Pedido criado."});return data.id}
export async function addHistory({orderId,empresaId,userId,type,description}){const{error}=await supabase.from("pedido_compra_historico").insert({pedido_id:orderId,empresa_id:String(empresaId),user_id:userId,tipo:type,descricao:description});if(error)throw error}
export async function changeOrderStatus({order,empresaId,userId,status}){const patch={status,updated_at:new Date().toISOString()};if(status==="Aprovado"){patch.aprovado_por=userId;patch.aprovado_em=new Date().toISOString()}const{error}=await supabase.from("pedidos_compra").update(patch).eq("id",order.id).eq("empresa_id",String(empresaId));if(error)throw error;const types={Solicitado:"Solicitação","Em cotação":"Cotação",Aprovado:"Aprovação",Comprado:"Compra",Cancelado:"Cancelamento"};await addHistory({orderId:order.id,empresaId,userId,type:types[status]||"Edição",description:`Status alterado para ${status}.`})}
export async function addQuote({orderId,empresaId,userId,quote}){const{error}=await supabase.from("pedido_compra_cotacoes").insert({pedido_id:orderId,empresa_id:String(empresaId),fornecedor_id:String(quote.supplier.id),fornecedor_snapshot:quote.supplier,valor_total:n(quote.value),prazo_dias:n(quote.days),custo_kg:n(quote.costKg),observacoes:quote.notes||null});if(error)throw error;await addHistory({orderId,empresaId,userId,type:"Cotação",description:`Cotação recebida de ${quote.supplier.nome}.`})}
export async function createInstallments({order,empresaId,userId,count,firstDue}){const total=Math.max(1,n(count));const value=order.valorTotal/total;const rows=Array.from({length:total},(_,index)=>{const due=new Date(`${firstDue}T12:00:00`);due.setMonth(due.getMonth()+index);return{pedido_id:order.id,empresa_id:String(empresaId),numero:index+1,vencimento:due.toISOString().slice(0,10),valor:index===total-1?order.valorTotal-value*(total-1):value}});const{error}=await supabase.from("pedido_compra_parcelas").upsert(rows,{onConflict:"pedido_id,numero"});if(error)throw error;await addHistory({orderId:order.id,empresaId,userId,type:"Financeiro",description:`${total} parcela(s) preparada(s) para contas a pagar.`})}
export async function receiveOrderItem({itemId,empresaId,quantity}){const{error}=await supabase.rpc("receber_item_pedido",{p_item_id:itemId,p_empresa_id:String(empresaId),p_quantidade:n(quantity)});if(error)throw error}
