import { useMemo, useState } from "react";
import useCompanyScope from "../../../app/providers/useCompanyScope";
import useAuth from "../../../app/providers/useAuth";
import { EmptyState, FeedbackBanner, FilterBar, LoadingState, MetricGrid, ModuleHeader } from "../../../components/operations/OperationsUI";
import useCustomers from "../../../hooks/useCustomers";
import { normalizeDigits, normalizeSearch, returnState } from "../services/prospeccao.service";
import { INTEREST_PRODUCTS, ORIGINS, PROSPECT_STATUSES } from "../types/prospeccao";
import useProspects from "../hooks/useProspects";
import InteractionModal from "../components/InteractionModal";
import ProspectDetails from "../components/ProspectDetails";
import ProspectFormModal from "../components/ProspectFormModal";
import "../prospeccao-comercial.css";
import { findProspectOpportunityLink, startProspectOpportunityFlow } from "../../../app/integrations/prospectCrmFlow";
import { startCustomerFlow } from "../../../app/integrations/customerCrmFlow";
import { linkOpportunityCustomer } from "../../crm-comercial/services/crm.service";

const formatDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const unique = (items) => [...new Set(items.filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR"));
export default function ProspeccaoComercialPage({ onNavigate }) {
  const { empresaId, userId, ready } = useCompanyScope();
  const { nomeUsuario } = useAuth();
  const data = useProspects({ empresaId, userId });
  const customers = useCustomers(empresaId);
  const [editing, setEditing] = useState(null); const [selectedId, setSelectedId] = useState(null); const [interactionTarget, setInteractionTarget] = useState(null); const [feedback, setFeedback] = useState(null);
  const selected = data.prospects.find((item) => item.id === selectedId) || null;
  const options = useMemo(() => ({ segmentos: unique(data.prospects.map((x) => x.segmento)), paises: unique(data.prospects.map((x) => x.pais || x.countryCode)), cidades: unique(data.prospects.map((x) => x.cidade)), estados: unique(data.prospects.map((x) => x.estado || x.region)), responsaveis: unique(data.prospects.map((x) => x.representante || x.responsavel)) }), [data.prospects]);
  const updateFilter = (key, value) => data.setFilters((current) => ({ ...current, [key]: value }));
  function saveProspect(item) {
    try {
      const saved = data.save(item);
      setEditing(null);
      setFeedback({ type: "success", message: item.id ? `Empresa “${saved.nomeFantasia || saved.razaoSocial}” atualizada com sucesso.` : "Empresa prospectada cadastrada com sucesso." });
    } catch (error) {
      setFeedback({ type: "error", message: error.message || "Não foi possível salvar a empresa prospectada." });
    }
  }
  function confirmDelete(item) { if (window.confirm(`Excluir a prospecção de ${item.nomeFantasia || item.razaoSocial}?`)) { data.remove(item.id); setSelectedId(null); setFeedback({ type: "success", message: "Prospecção excluída." }); } }
  async function convert(item) {
    if (item.convertidoClienteId) return openCustomer(item);
    const duplicate = customers.customers.find((customer) => (item.cnpj && normalizeDigits(customer.cpf_cnpj || customer.cnpj) === normalizeDigits(item.cnpj)) || (item.email && normalizeSearch(customer.email) === normalizeSearch(item.email)) || ((item.telefone || item.whatsapp) && normalizeDigits(customer.telefone) === normalizeDigits(item.telefone || item.whatsapp)));
    if (duplicate) return setFeedback({ type: "error", message: `Conversão bloqueada: já existe o cliente “${duplicate.nome}” com dados equivalentes.` });
    if (!window.confirm(`Converter ${item.nomeFantasia || item.razaoSocial} em cliente?`)) return;
    try { const customer = await customers.save({ nome: item.nomeFantasia || item.razaoSocial, telefone: item.telefone || item.whatsapp, email: item.email }); data.patch(item.id, { status: "Convertido em cliente", convertidoClienteId: customer.id, convertidoEm: new Date().toISOString() }); const link=findProspectOpportunityLink({empresaId,userId,prospectId:item.id}); if(link) await linkOpportunityCustomer({empresaId,opportunityId:link.opportunityId,customerId:customer.id}); setFeedback({ type: "success", message: link ? "Cliente criado e oportunidade existente vinculada com sucesso." : "Cliente criado. Esta prospecção não possui vínculo inequívoco com uma oportunidade existente." }); }
    catch (error) { setFeedback({ type: "error", message: error.message || "Não foi possível converter em cliente." }); }
  }
  function openCustomer(item) {
    if (!item.convertidoClienteId) return;
    startCustomerFlow({empresaId,customerId:item.convertidoClienteId});
    onNavigate?.("clientes");
    const link=findProspectOpportunityLink({empresaId,userId,prospectId:item.id});
    if(link) void linkOpportunityCustomer({empresaId,opportunityId:link.opportunityId,customerId:item.convertidoClienteId}).catch((error)=>console.error("Não foi possível reconciliar a oportunidade ao abrir o cliente.",error));
  }
  function createOpportunity(item) {
    startProspectOpportunityFlow({ prospect: item, empresaId, userId });
    onNavigate?.("crm");
  }
  return <main className="ops-page prospect-page"><ModuleHeader eyebrow="Comercial" title="Prospecção Comercial" description="Cadastre, acompanhe e converta empresas potenciais com histórico e retornos organizados." actionLabel="Nova empresa" onAction={() => setEditing({})} />
    <div className="prospect-storage-note"><span /> Persistência local temporária, isolada por empresa e usuário</div><FeedbackBanner feedback={feedback} onClose={() => setFeedback(null)} />{data.error && <FeedbackBanner feedback={{ type: "error", message: data.error }} />}
    <MetricGrid items={[{ label: "Empresas prospectadas", value: data.metrics.total, detail: "registros reais", icon: "▦" }, { label: "Novos contatos", value: data.metrics.novos, detail: "status Novo", icon: "+" }, { label: "Empresas em contato", value: data.metrics.contato, detail: "contato em andamento", icon: "☎" }, { label: "Em negociação", value: data.metrics.negociacao, detail: "funil avançado", icon: "◎", tone: "amber" }, { label: "Clientes convertidos", value: data.metrics.convertidos, detail: "vinculados a Clientes", icon: "✓", tone: "green" }, { label: "Retornos pendentes", value: data.metrics.pendentes, detail: "hoje ou vencidos", icon: "!", tone: "rose" }, { label: "Sem interação recente", value: data.metrics.semInteracao, detail: "há mais de 30 dias", icon: "◇" }]} />
    <FilterBar><input className="prospect-search" placeholder="Buscar empresa, contato, CNPJ, telefone, cidade, produto..." value={data.filters.search} onChange={(e) => updateFilter("search", e.target.value)} /><select value={data.filters.status} onChange={(e) => updateFilter("status", e.target.value)}><option value="">Todos os status</option>{PROSPECT_STATUSES.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.segmento} onChange={(e) => updateFilter("segmento", e.target.value)}><option value="">Segmentos</option>{options.segmentos.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.cidade} onChange={(e) => updateFilter("cidade", e.target.value)}><option value="">Cidades</option>{options.cidades.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.estado} onChange={(e) => updateFilter("estado", e.target.value)}><option value="">Estados</option>{options.estados.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.responsavel} onChange={(e) => updateFilter("responsavel", e.target.value)}><option value="">Responsáveis</option>{options.responsaveis.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.produto} onChange={(e) => updateFilter("produto", e.target.value)}><option value="">Produtos</option>{INTEREST_PRODUCTS.map((v) => <option key={v}>{v}</option>)}</select><select value={data.filters.origem} onChange={(e) => updateFilter("origem", e.target.value)}><option value="">Origens</option>{ORIGINS.map((v) => <option key={v}>{v}</option>)}</select><label className="prospect-filter-date"><span>Último contato</span><input type="date" value={data.filters.ultimaInteracao} onChange={(e) => updateFilter("ultimaInteracao", e.target.value)} /></label><label className="prospect-filter-date"><span>Próximo retorno</span><input type="date" value={data.filters.proximoRetorno} onChange={(e) => updateFilter("proximoRetorno", e.target.value)} /></label><label className="prospect-filter-check"><input type="checkbox" checked={data.filters.retornoVencido} onChange={(e) => updateFilter("retornoVencido", e.target.checked)} /> Retorno vencido</label><label className="prospect-filter-check"><input type="checkbox" checked={data.filters.semContatoRecente} onChange={(e) => updateFilter("semContatoRecente", e.target.checked)} /> Sem contato recente</label><button onClick={data.clearFilters}>Limpar</button></FilterBar>
    <section className="ops-panel"><div className="ops-panel__header"><h2>Empresas prospectadas</h2><span>{data.filtered.length} resultado(s)</span></div>{data.loading ? <LoadingState>Carregando prospecções...</LoadingState> : !data.filtered.length ? <EmptyState title="Nenhuma empresa prospectada encontrada" description="Cadastre uma empresa ou ajuste os filtros." /> : <div className="ops-table-wrap"><table className="ops-table prospect-table"><thead><tr><th>Empresa</th><th>Segmento</th><th>Cidade/UF</th><th>Contato</th><th>Telefone/WhatsApp</th><th>E-mail</th><th>Produtos</th><th>Origem</th><th>Status</th><th>Última interação</th><th>Próximo retorno</th><th>Responsável</th><th>Ações</th></tr></thead><tbody>{data.filtered.map((item) => { const last = [...(item.interacoes || [])].sort((a,b) => String(b.dataHora).localeCompare(String(a.dataHora)))[0]; const linked=Boolean(findProspectOpportunityLink({empresaId,userId,prospectId:item.id})); return <tr key={item.id}><td><strong>{item.nomeFantasia || item.razaoSocial}</strong><small>{item.cnpj || "CNPJ não informado"}</small></td><td>{item.segmento || "—"}</td><td>{[item.cidade, item.estado].filter(Boolean).join("/") || "—"}</td><td>{item.contatoNome || "—"}</td><td>{item.whatsapp || item.telefone || "—"}</td><td>{item.email || "—"}</td><td>{(item.produtosInteresse || []).join(", ") || "—"}</td><td>{item.origem || "—"}</td><td><select value={item.status} onChange={(e) => data.patch(item.id, { status: e.target.value, arquivado: e.target.value === "Arquivado" })}>{PROSPECT_STATUSES.map((v) => <option key={v}>{v}</option>)}</select></td><td>{formatDate(last?.dataHora)}</td><td><span className={`prospect-return prospect-return--${returnState(item.proximoRetornoEm)}`}>{formatDate(item.proximoRetornoEm)}</span></td><td>{item.responsavel || "—"}</td><td><div className="prospect-row-actions"><button type="button" className="prospect-edit-action" title="Editar empresa" aria-label={`Editar empresa ${item.nomeFantasia || item.razaoSocial}`} onClick={() => setEditing(item)}>✎ Editar</button><button type="button" onClick={() => setSelectedId(item.id)}>Visualizar</button><button type="button" onClick={() => setInteractionTarget(item)}>Interação</button><button type="button" title={linked?"Abrir oportunidade existente no CRM":"Criar oportunidade no CRM"} onClick={() => createOpportunity(item)}>{linked?"Abrir oportunidade no CRM":"Criar oportunidade no CRM"}</button>{item.convertidoClienteId?<button type="button" onClick={() => openCustomer(item)}>Abrir cliente</button>:<button type="button" onClick={() => convert(item)}>Converter</button>}<button type="button" onClick={() => data.patch(item.id, { status: item.status === "Arquivado" ? "Novo" : "Arquivado", arquivado: item.status !== "Arquivado" })}>{item.status === "Arquivado" ? "Reabrir" : "Arquivar"}</button><button type="button" className="danger" onClick={() => confirmDelete(item)}>Excluir</button></div></td></tr>; })}</tbody></table></div>}</section>
    {editing && <ProspectFormModal prospect={editing.id ? editing : null} onClose={() => setEditing(null)} onSave={saveProspect} />}{interactionTarget && <InteractionModal prospect={interactionTarget} defaultResponsible={nomeUsuario} onClose={() => setInteractionTarget(null)} onSave={(interaction) => { data.addInteraction(interactionTarget.id, interaction); setInteractionTarget(null); setFeedback({ type: "success", message: "Interação registrada." }); }} />}{selected && <ProspectDetails prospect={selected} opportunityLinked={Boolean(findProspectOpportunityLink({empresaId,userId,prospectId:selected.id}))} onClose={() => setSelectedId(null)} onEdit={() => { setEditing(selected); setSelectedId(null); }} onInteraction={() => { setInteractionTarget(selected); setSelectedId(null); }} onConvert={() => { void convert(selected); setSelectedId(null); }} onOpenCustomer={() => { void openCustomer(selected); setSelectedId(null); }} onOpportunity={createOpportunity} onArchive={() => { data.patch(selected.id, { status: selected.status === "Arquivado" ? "Novo" : "Arquivado" }); setSelectedId(null); }} onDelete={() => confirmDelete(selected)} />}
    {!ready && <div className="prospect-disabled">Aguardando identificação segura da empresa e do usuário.</div>}
  </main>;
}
