import { returnState } from "../services/prospeccao.service";

const formatDate = (value) => value ? new Date(value).toLocaleString("pt-BR") : "—";
export default function ProspectDetails({ prospect, onClose, onEdit, onInteraction, onConvert, onOpportunity, onArchive, onDelete }) {
  if (!prospect) return null;
  const interactions = [...(prospect.interacoes || [])].sort((a, b) => String(b.dataHora).localeCompare(String(a.dataHora)));
  return <div className="crm-details-overlay" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><aside className="crm-details prospect-details"><header><div><small>{prospect.status}</small><h2>{prospect.nomeFantasia || prospect.razaoSocial}</h2><p>{prospect.segmento || "Segmento não informado"}</p></div><button onClick={onClose}>×</button></header>
    <div className="prospect-detail-actions"><button onClick={onEdit}>Editar</button><button onClick={onInteraction}>Registrar interação</button><button onClick={onOpportunity}>Criar oportunidade</button><button onClick={onConvert}>Converter em cliente</button><button onClick={onArchive}>{prospect.status === "Arquivado" ? "Reabrir" : "Arquivar"}</button><button className="danger" onClick={onDelete}>Excluir</button></div>
    <section className="crm-detail-grid">{[["Razão social", prospect.razaoSocial], ["Identificação fiscal", prospect.cnpj], ["Contato", prospect.contatoNome], ["Cargo", prospect.contatoCargo], ["Telefone", prospect.telefone], ["WhatsApp", prospect.whatsapp], ["E-mail", prospect.email], ["País", prospect.pais || prospect.countryCode], ["Localidade", [prospect.cidade, prospect.estado || prospect.region].filter(Boolean).join("/")], ["Código postal", prospect.codigoPostal || prospect.postalCode], ["Idioma", prospect.idiomaPreferencial || prospect.preferredLocale], ["Moeda", prospect.moedaPreferencial || prospect.preferredCurrency], ["Fuso horário", prospect.fusoHorario || prospect.timeZone], ["Origem", prospect.origem], ["Representante", prospect.representante || prospect.responsavel], ["Produtos", (prospect.produtosInteresse || []).join(", ")], ["Próximo retorno", formatDate(prospect.proximoRetornoEm)]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || "—"}</strong></div>)}</section>
    <section className={`prospect-return-card prospect-return-card--${returnState(prospect.proximoRetornoEm)}`}><strong>Retorno comercial</strong><span>{prospect.retornoObservacao || "Nenhuma observação registrada."}</span></section>
    <section className="crm-notes"><h3>Necessidade e observações</h3><p>{prospect.necessidade || "Nenhuma necessidade descrita."}</p><p>{prospect.observacoes || "Nenhuma observação comercial."}</p></section>
    <section className="crm-activity"><div><h3>Histórico de interações</h3><small>Mais recente primeiro</small></div><div className="crm-timeline">{interactions.length ? interactions.map((item) => <article key={item.id}><span>•</span><div><strong>{item.tipo} · {item.responsavel || "Sem responsável"}</strong><p>{item.resumo}</p><small>{formatDate(item.dataHora)}{item.resultado ? ` · ${item.resultado}` : ""}</small></div></article>) : <p className="crm-no-activity">Nenhuma interação registrada.</p>}</div></section>
  </aside></div>;
}
