import { useCallback, useEffect, useMemo, useState } from "react";
import { addOpportunityHistory, deleteOpportunityRecord, listOpportunities, saveOpportunityRecord, updateOpportunityStage } from "../services/crm.service";
import { OPEN_STAGES } from "../types/crm";
import { loadProspects } from "../../prospeccao-comercial/services/prospeccao.service";
import { enrichOpportunitiesFromProspects } from "../../../app/integrations/prospectCrmFlow";
const initialFilters = { search: "", vendedor: "", etapa: "", prioridade: "", segmento: "", inicio: "", fim: "" };
export default function useCrm({ empresaId, userId }) {
  const [opportunities,setOpportunities]=useState([]); const [prospects,setProspects]=useState([]); const [filters,setFilters]=useState(initialFilters); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const refresh=useCallback(async()=>{if(!empresaId)return false;setLoading(true);setError("");try{const [remote,prospectData]=await Promise.all([listOpportunities(empresaId),loadProspects({empresaId,userId})]);setProspects(prospectData);setOpportunities(enrichOpportunitiesFromProspects({opportunities:remote,prospects:prospectData}));return true;}catch(e){console.error("[CRM] Releitura das oportunidades falhou",e);setError(e.message||"Não foi possível carregar o CRM persistente.");return false;}finally{setLoading(false);}},[empresaId,userId]);
  useEffect(()=>{const timer=window.setTimeout(refresh,0);return()=>window.clearTimeout(timer);},[refresh]);
  const filtered=useMemo(()=>opportunities.filter((item)=>{const term=filters.search.toLowerCase();const date=item.proximoContato||item.createdAt||"";return [item.empresa,item.contatoPrincipal,item.produtoInteresse,item.cidade].some((v)=>String(v).toLowerCase().includes(term))&&(!filters.vendedor||item.vendedorResponsavel===filters.vendedor)&&(!filters.etapa||item.etapa===filters.etapa)&&(!filters.prioridade||item.prioridade===filters.prioridade)&&(!filters.segmento||item.segmento===filters.segmento)&&(!filters.inicio||date>=filters.inicio)&&(!filters.fim||date<=filters.fim);}),[filters,opportunities]);
  const metrics=useMemo(()=>{const abertas=opportunities.filter((i)=>OPEN_STAGES.includes(i.etapa));const ganhos=opportunities.filter((i)=>i.etapa==="Fechado — ganho").length;const perdidos=opportunities.filter((i)=>i.etapa==="Fechado — perdido").length;return{abertas:abertas.length,valorFunil:abertas.reduce((s,i)=>s+Number(i.valorEstimado||0),0),propostas:opportunities.filter((i)=>i.etapa==="Proposta enviada").length,negociacoes:opportunities.filter((i)=>i.etapa==="Negociação").length,ganhos,perdidos,conversao:ganhos+perdidos?ganhos/(ganhos+perdidos)*100:0,vencidos:0,hoje:0};},[opportunities]);
  async function saveOpportunity(data){const saved=await saveOpportunityRecord({opportunity:data,empresaId,userId});setOpportunities((current)=>data.id?current.map((item)=>item.id===saved.id?saved:item):[saved,...current.filter((item)=>item.id!==saved.id)]);const refreshed=await refresh();return{...saved,refreshWarning:refreshed?"":"Oportunidade gravada, mas a listagem não pôde ser recarregada."};}
  async function moveOpportunity(id,stage){if(stage.startsWith("Fechado")&&!window.confirm(`Confirmar mudança para ${stage}?`))return;await updateOpportunityStage({id,stage,empresaId,userId});await refresh();}
  async function addActivity(id,activity){await addOpportunityHistory({opportunityId:id,empresaId,userId,type:activity.tipo,description:activity.descricao});await refresh();}
  async function removeOpportunity(id){if(!window.confirm("Excluir permanentemente esta oportunidade e seu histórico?"))return;await deleteOpportunityRecord({id,empresaId});await refresh();}
  const clearFilters=useCallback(()=>setFilters(initialFilters),[]);
  return{opportunities,prospects,filtered,filters,setFilters,clearFilters,metrics,saveOpportunity,moveOpportunity,addActivity,removeOpportunity,loading,error};
}
