-- Menor privilégio para os papéis expostos pela Data API.
-- Inventário remoto de 2026-08-30: somente privilégios DDL são removidos.
-- REVOKE é idempotente: repetir estes comandos preserva o mesmo estado final.

revoke truncate, trigger, references on table
  public.assinaturas,
  public.catalogo_importacoes,
  public.catalogo_produtos,
  public.categorias,
  public.configuracoes,
  public.contas,
  public.contas_pagar,
  public.crm_oportunidade_historico,
  public.crm_oportunidades,
  public.empresa_alertas_tributarios,
  public.empresa_configuracoes_tributarias,
  public.empresa_regras_tributarias,
  public.emprestimos,
  public.estoque,
  public.estoque_movimentacoes,
  public.financeiro_baixas,
  public.financeiro_conciliacoes,
  public.financeiro_historico,
  public.financeiro_titulos,
  public.fornecedores,
  public.ia_comercial_historico,
  public.inventario_itens,
  public.inventarios,
  public.lancamentos_pessoais,
  public.orcamento_aprovacoes,
  public.orcamento_historico,
  public.orcamento_itens,
  public.orcamentos,
  public.ordem_producao_apontamentos,
  public.ordem_producao_custos,
  public.ordem_producao_historico,
  public.ordem_producao_materiais,
  public.ordem_producao_operacao_apontamentos,
  public.ordem_producao_operacao_resultados,
  public.ordem_producao_recursos,
  public.ordens_producao,
  public.parcelas,
  public.pedido_compra_cotacoes,
  public.pedido_compra_followups,
  public.pedido_compra_historico,
  public.pedido_compra_itens,
  public.pedido_compra_parcelas,
  public.pedidos_compra,
  public.produtos,
  public.prospeccao_interacoes,
  public.prospeccao_prospectos,
  public.recebimentos,
  public.recurso_producao_indisponibilidades,
  public.recursos_producao
from anon;

revoke truncate, trigger, references on table
  public.assinaturas,
  public.catalogo_importacoes,
  public.catalogo_produtos,
  public.categorias,
  public.clientes,
  public.compras,
  public.configuracoes,
  public.contas,
  public.contas_pagar,
  public.crm_oportunidade_historico,
  public.crm_oportunidades,
  public.empresa_modulos,
  public.emprestimos,
  public.estoque,
  public.estoque_movimentacoes,
  public.financeiro_baixas,
  public.financeiro_conciliacoes,
  public.financeiro_historico,
  public.financeiro_titulos,
  public.fornecedores,
  public.ia_comercial_historico,
  public.inventario_itens,
  public.inventarios,
  public.lancamentos,
  public.lancamentos_pessoais,
  public.orcamento_aprovacoes,
  public.orcamento_historico,
  public.orcamento_itens,
  public.orcamentos,
  public.ordem_producao_apontamentos,
  public.ordem_producao_custos,
  public.ordem_producao_historico,
  public.ordem_producao_materiais,
  public.ordem_producao_operacao_apontamentos,
  public.ordem_producao_operacao_resultados,
  public.ordem_producao_recursos,
  public.ordens_producao,
  public.parcelas,
  public.pedido_compra_cotacoes,
  public.pedido_compra_followups,
  public.pedido_compra_historico,
  public.pedido_compra_itens,
  public.pedido_compra_parcelas,
  public.pedidos_compra,
  public.plano_modulos,
  public.planos,
  public.produtos,
  public.prospeccao_interacoes,
  public.prospeccao_prospectos,
  public.recebimentos,
  public.recurso_producao_indisponibilidades,
  public.recursos_producao,
  public.vendas
from authenticated;

revoke trigger, references on table
  public.empresa_alertas_tributarios,
  public.empresa_configuracoes_tributarias,
  public.empresa_nota_fiscal_analises,
  public.empresa_nota_fiscal_itens,
  public.empresa_notas_fiscais_tributarias,
  public.empresa_regras_tributarias,
  public.empresa_verificacoes_tributarias,
  public.empresas
from authenticated;
