import PersonalFinanceCharts from "../components/PersonalFinanceCharts";
import PersonalFinanceHeader from "../components/PersonalFinanceHeader";
import PersonalFinanceMetrics from "../components/PersonalFinanceMetrics";
import PersonalFinanceSummary from "../components/PersonalFinanceSummary";
import { DEMO_COMMISSIONS, DEMO_INCOMES, DEMO_MONTHS } from "../services/personalFinance.demo";
import { money, netIncome } from "../utils/personalFinance";

export default function FinanceiroPessoalDashboard() {
  const expected = DEMO_INCOMES.filter((item) => item.status !== "Recebida").reduce((sum, item) => sum + netIncome(item), 0);
  const received = DEMO_INCOMES.filter((item) => item.status === "Recebida").reduce((sum, item) => sum + netIncome(item), 0);
  const current = DEMO_MONTHS.at(-1); const previous = DEMO_MONTHS.at(-2);
  const plannedExpense = current.expense; const paidExpense = Math.round(current.expense * .76);
  return <main className="ops-page pf-page"><PersonalFinanceHeader title="Visão Geral Pessoal" description="Receitas, gastos e metas pessoais sem mistura com o financeiro empresarial." />
    <div className="pf-demo-badge">Painel demonstrativo · persistência pessoal será definida em fase futura</div>
    <PersonalFinanceMetrics items={[{ label: "Receitas previstas", value: money(expected), detail: "mês atual", icon: "↗" }, { label: "Receitas recebidas", value: money(received), detail: "confirmadas", icon: "✓", tone: "green" }, { label: "Gastos previstos", value: money(plannedExpense), detail: "mês atual", icon: "↘", tone: "amber" }, { label: "Gastos pagos", value: money(paidExpense), detail: "realizados", icon: "✓" }, { label: "Saldo previsto", value: money(expected + received - plannedExpense), detail: "projeção", icon: "R$", tone: "green" }, { label: "Saldo realizado", value: money(received - paidExpense), detail: "até agora", icon: "◎" }, { label: "Contas vencendo", value: "4", detail: "próximos 7 dias", icon: "◷" }, { label: "Contas atrasadas", value: "2", detail: "requer atenção", icon: "!", tone: "rose" }, { label: "Renda comprometida", value: "63%", detail: "limite sugerido 70%", icon: "%", tone: "amber" }, { label: "Economia do mês", value: money(current.income - current.expense), detail: `${Math.round((current.income - current.expense) / current.income * 100)}% da renda`, icon: "◇", tone: "green" }]} />
    <PersonalFinanceCharts />
    <section className="pf-summary-grid"><PersonalFinanceSummary title="Próximos vencimentos" subtitle="Agenda demonstrativa"><ul><li><span>Aluguel</span><b>Dia 05 · {money(2450)}</b></li><li><span>Energia</span><b>Dia 08 · {money(286)}</b></li><li><span>Cartão</span><b>Dia 12 · {money(1840)}</b></li></ul></PersonalFinanceSummary><PersonalFinanceSummary title="Receitas aguardando" subtitle="Em memória"><ul>{DEMO_INCOMES.filter((item) => item.status === "Prevista").map((item) => <li key={item.id}><span>{item.descricao}</span><b>{money(netIncome(item))}</b></li>)}</ul></PersonalFinanceSummary><PersonalFinanceSummary title="Maiores gastos" subtitle="Mês demonstrativo"><ul><li><span>Moradia</span><b>{money(2450)}</b></li><li><span>Cartão</span><b>{money(1840)}</b></li><li><span>Alimentação</span><b>{money(1260)}</b></li></ul></PersonalFinanceSummary><PersonalFinanceSummary title="Resumo fixas" subtitle="Projeção"><div className="pf-big-number"><strong>{money(4120)}</strong><small>6 contas · 50,2% dos gastos</small></div></PersonalFinanceSummary><PersonalFinanceSummary title="Meta de economia" subtitle="Objetivo mensal"><div className="pf-goal"><div><span style={{ width: "74%" }} /></div><strong>74% alcançado</strong><small>{money(3700)} de {money(5000)}</small></div></PersonalFinanceSummary><PersonalFinanceSummary title="Comissões previstas" subtitle="Integração futura"><ul>{DEMO_COMMISSIONS.map((item) => <li key={item.sale}><span>{item.sale} · {item.client}</span><b>{money(item.expected)}</b></li>)}</ul></PersonalFinanceSummary></section>
    <div className="pf-month-comparison">Saldo anterior: <strong>{money(previous.income - previous.expense)}</strong> · Saldo atual: <strong>{money(current.income - current.expense)}</strong></div>
  </main>;
}
